### ISSUE TITLE
Backlight brightness levels

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#109]
I think if the LCB_BL line is on a PWM channel, we can support multiple backlight brightness levels. On Electronics version 0.9 LCD_BL is on PF7, which does not support PWM.

To implement this the LCD_BL pin will have to be swapped with something attached to a PWM pin.

This photo shows some PWM pin options.
![screen shot 2014-12-23 at 12 21 14](https://cloud.githubusercontent.com/assets/281642/5534535/35fb0b50-8a9e-11e4-8e16-d43620e5726a.png)

**Comment by charlespax** [comment]
@samchoy88 can you get LCD_BL on one of the PWM channels in Electronics version 0.10? Otherwise, we'll have to address this int he next board revision.

**Comment by samchoy88** [comment]
Assigned LCD_BL to D6. (PWM available)
![image](https://cloud.githubusercontent.com/assets/1327611/5891375/579023b6-a4cc-11e4-8b13-af4198fd9890.png)

**Comment by charlespax** [comment]
Cool. Closing issue.

**Comment by charlespax** [comment]
Tested and working on 0.10 PCB.
