### ISSUE TITLE
Super capacitor as RTC backup

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#113]
There is potential for using a super capacitor as the RTC backup rather than a battery. This has been discussed in issue https://github.com/PaxInstruments/t400-electronics/issues/1.

**Comment by charlespax** [comment]
This is still a cool idea, but right now we're sticking with the battery. Moving to Electronics version :-)

**Comment by charlespax** [comment]
Will not do. Closing issue.

**Comment by NuclearPhoenixx** [comment]
The problem with rechargable batteries is that you need relatively complicated charging curcuits. For the super caps, you need a diode and a resistor, that's it basically. Also there are already super caps with [6.8mm diameter, but 0.3F(!) capacitance](https://datasheet.lcsc.com/szlcsc/0-3F-3-3V_C122504.pdf). This would give you 10 times as much backup time (41 days!) at less than double the diameter.
