### ISSUE TITLE
JP1 made circuit operate at 3.6V instead of 3.3V

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#117]
![image](https://cloud.githubusercontent.com/assets/1327611/5581282/6342bc76-9092-11e4-8e0c-2c96d6314036.png)

I found the circuit operate at 3.6V instead of 3.3V and suspect the power circuit has some problem.
Finally found the short circut of JP1 not only made the circuit always ON, it also inject 5V to MCU I/O pin (PWR_ONOFF) and made the whole circuit voltage rise to 3.6V

**Comment by charlespax** [comment]
Cool. Let's keep that resistor on the component side and have it populated. Maybe we unpopulated it later, but this is a good default for now.

**Comment by charlespax** [comment]
@samchoy88 is this still an issue or is it addressed in Electronics version 0.10?

**Comment by samchoy88** [comment]
addressed in Rev 0.10

**Comment by samchoy88** [comment]
addressed in Rev 0.10

**Comment by charlespax** [comment]
Cool. Closing issue.
