### ISSUE TITLE
Power on/off output low

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#118]
Power on/off goes output low and turns the system off all the time.

(From our discussion at lunch.)

**Comment by samchoy88** [comment]
As the PWR_ONOFF pin set as output Low initially, it cause the systemturn off after JP1 has been shorted.
![image](https://cloud.githubusercontent.com/assets/1327611/5609749/a2b4c148-94e2-11e4-90c6-997f2d3031bd.png)

I may change circuit design to prevent this issue.

**Comment by charlespax** [comment]
Background: the purpose of having JP1 in this design is to aid development by having an easy way to keep the device always using hardware rather than software.

If the jumper is not shorted and the power switched is pressed, the system will boot and set PWR_ONOFF to HIGH. Then the system will stay on until PWR_ONOFF is set to LOW.

If the jumper is shorted and PWR_ONOFF is set to LOW, logic input A will be LOW. If there were no 1k resistor in series with JP1, there would be a short, which is bad.

If the jumper is shorted and PWR_ONOFF is set to HIGH, logic input A is always HIGH. No problems in this case.

I think we need a jumper that can short logic input A to VBUS and a resistor between PWR_ONOFF and logic input A. In this case the Jumper can be shorted to VBUS and always keep logic input A HIGH. PWR_ONOFF can be high or low and not be shorted to GND because there would be a resistor.

**Comment by samchoy88** [comment]
#134

**Comment by charlespax** [comment]
How was it modified? Screenshot please.

**Comment by samchoy88** [comment]
Changed logic gate to NAND gate. All switch and jumper pin will trigger the circuit by Low level.

Before:
![image](https://cloud.githubusercontent.com/assets/1327611/5609749/a2b4c148-94e2-11e4-90c6-997f2d3031bd.png)

After:
![image](https://cloud.githubusercontent.com/assets/1327611/5776962/1b89aa18-9dc9-11e4-83e7-72336a90f0e6.png)

**Comment by charlespax** [comment]
Beautiful :-)

**Comment by MLXXXp** [comment]
I thought you were going to increase the value of the pullups from 10K to 100K, as per comments in issue #134.

**Comment by samchoy88** [comment]
You're correct.
![image](https://cloud.githubusercontent.com/assets/1327611/5779322/d8cc987a-9ddc-11e4-9cab-8c825a1107d6.png)

**Comment by charlespax** [comment]
Done. Closing issue.
