### ISSUE TITLE
Resistors are close to RTC battery

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#119]
There are resistors that are a little too close to the RTC battery connector.

(From our discussion at lunch.)

**Comment by samchoy88** [comment]
Yes, I feel a little bit danger around the RTC battery connector.
Short circuit may happen.
![image](https://cloud.githubusercontent.com/assets/1327611/5609823/28afab86-94e4-11e4-83e4-dddc6d0513eb.png)

**Comment by charlespax** [comment]
Agreed. let's fix this in Electronics version 0.10.

**Comment by samchoy88** [comment]
Less component place nearby RTC battery in Rev 0.10 board.
![image](https://cloud.githubusercontent.com/assets/1327611/5891951/8b66e9be-a4e9-11e4-8a56-e428411e35cd.png)

**Comment by charlespax** [comment]
Closing issue.
