### ISSUE TITLE
Resistors are close together

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#120]
There are some resistors that are a bit close together. Switching to 0603 (https://github.com/PaxInstruments/t400-electronics/issues/121) should solve this.

(From our discussion at lunch.)

**Comment by samchoy88** [comment]
Yes, I found the resistor are too close at the area of 3.3Reg part. It made a little bit difficult to solder by hand.
![image](https://cloud.githubusercontent.com/assets/1327611/5609680/f3fccc78-94e0-11e4-9f8e-3efb9dc67889.png)

**Comment by samchoy88** [comment]
Yes, I found the resistor are too close at the area of 3.3Reg part. It made a little bit difficult to solder by hand.
![image](https://cloud.githubusercontent.com/assets/1327611/5609680/f3fccc78-94e0-11e4-9f8e-3efb9dc67889.png)

**Comment by charlespax** [comment]
Let's increase the distance in Electronics version 0.10.

**Comment by samchoy88** [comment]
Switched to 0603 resistor and capacitor does not improve much on space.
They looks almost compatible to each other.
Capacitor in Yellow is 0805, Green is 0603

It seem I need to find a better place and space for these circuit.

![image](https://cloud.githubusercontent.com/assets/1327611/5642907/2d746c66-968c-11e4-95e6-f6a220ad9f0e.png)

**Comment by samchoy88** [comment]
More space between resistors in Rev 0.10
![image](https://cloud.githubusercontent.com/assets/1327611/5891957/dbdfd054-a4e9-11e4-89c4-c3f822c8d799.png)

**Comment by charlespax** [comment]
Closing issue.
