### ISSUE TITLE
Switch to 0603

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#121]
Maybe we should switch from 0805 to 0603.

(From our discussion at lunch.)

**Comment by charlespax** [comment]
Moving to the Electronics version 0.10 milestone. @samchoy88 are we still fully moving to 0603 or are you leaving some components at 0805?

**Comment by samchoy88** [comment]
All caps and resistors using 0603 package in Rev 0.10 currently.
Last update (8c606fb) fixed all caps and resistors to 0603 (No 0805 package anymore).

**Comment by charlespax** [comment]
Okay, closing issue.
