### ISSUE TITLE
Longer solder pads on 2x3 header footprint

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#122]
If we use the SIM card connector, we may want to make the 2x3 header footprint longer, so they do not have to be aligned perfectly.

**Comment by samchoy88** [comment]
the programming port will apply larger pad that fit with SIM card connector:
![image](https://cloud.githubusercontent.com/assets/1327611/5609553/3c7ab97c-94de-11e4-8b99-db3fa644b8a6.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5609556/6d91413e-94de-11e4-98a2-fcfbc95bdc6e.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5609560/88e2f4a0-94de-11e4-920e-2db05a7fb40a.png)

**Comment by charlespax** [comment]
Cool. Let's get this in Electronics version 0.10.

**Comment by samchoy88** [comment]
Library changed but not significant.

Before:
![image](https://cloud.githubusercontent.com/assets/1327611/5642305/12b0ce60-9682-11e4-92eb-77c96f9bfb3f.png)

After:
![image](https://cloud.githubusercontent.com/assets/1327611/5642307/2df42c62-9682-11e4-8a1d-795c46ad55a3.png)

**Comment by samchoy88** [comment]
Due to limitation of the space, we give up the longer pads on 2x3 header footprint.
Changed back to normal size.

**Comment by charlespax** [comment]
Moving issue to Electronics version :-)

**Comment by charlespax** [comment]
Will not do. Closing issue.
