### ISSUE TITLE
Inductor between isothermal plane and GND

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#123]
Maybe we should use an inductor between the isothermal plane and ground.

(From our discussion at lunch.)

**Comment by samchoy88** [comment]
Currently the Analog ground and Digital ground are connected by Ferrite Bead which can supresses high frequency noise pass though it. Hope it helps.

**Comment by charlespax** [comment]
The most recent version in git still has a 10k resistor. The prototype board you made have the ferrite bead instead?

![screen shot 2015-01-05 at 14 28 59](https://cloud.githubusercontent.com/assets/281642/5609936/35158d52-94e7-11e4-9d49-70b526164d77.png)

**Comment by samchoy88** [comment]
Yes, the prototype board I made have the Ferrite bead instead. Let see the result.

**Comment by charlespax** [comment]
Let's make the change for Electronics version 0.10. If it doesn't work out, we can revert.

**Comment by charlespax** [comment]
From our conversation we have decided to use a zero ohm resistor. We should make a component for the library that is a resistor pad set with a trace linking them.

**Comment by samchoy88** [comment]
I found the ground should use zero resistor instead.
However, the isothermal ground (Analog ground) and Normal ground should connect near power supply.
However, I cant find a good position for the power supply to achieve this. Any suggestion on this?
![image](https://cloud.githubusercontent.com/assets/1327611/5644205/067a0796-969c-11e4-89a2-6dcc9168dea1.png)

**Comment by charlespax** [comment]
Whether the device is powered via USB or battery all the power goes through the 3.3 V regulator circled in the image below. Maybe I don't fully understand the concept, but I don't think the charging portion has much to do with this.

![screen shot 2015-01-16 at 00 07 19 copy](https://cloud.githubusercontent.com/assets/281642/5761090/0b4e1554-9d14-11e4-9e82-c70ab5fcbc65.png)

Can we run a trace from the isothermal ground to near the 3.3 V regulator?

**Comment by samchoy88** [comment]
Here is the schematic for reference
![image](https://cloud.githubusercontent.com/assets/1327611/5761346/d70e1576-9d15-11e4-8538-0c02b192d842.png)

As you can see the system can power by 2 different source, USB and Battery.
- You will find the current pass through the bottom part to charge battery and battery past through the bottom part back to regulator and supply the whole circuit by 3.3V.
- Besides, the analog GND must past through the noise digital GND to get back power supply (orange path). This made the Analog part noise and it may affect accuracy of the reading.

![image](https://cloud.githubusercontent.com/assets/1327611/5761497/c9e1e41c-9d16-11e4-8de3-0422eb79617b.png)

here is my suggestion:
- Move the all noisy digital component (SD card and Flash) to left hand side.
- RTC and its battery move to right hand side and made more space for regulator, charger

**Comment by charlespax** [comment]
I see no problem with moving the SD card and flash to the left side. However, we need feedback from @starno. @starno what do you think?

What will happen with the BL-5C batter connector? Will that get moved to the left side too? That would require significant work on the enclosure, but is doable. @starno any thoughts on this part?

**Comment by samchoy88** [comment]
Why BL-5C connector move together with SD-card connector?

**Comment by charlespax** [comment]
It doesn't have to. It jus sounded like you wanted to move the battery connector too because it is part of the power system on the right side.

**Comment by samchoy88** [comment]
Yes, the battery connector at bottom right side is OK. As the circuit density is low and it seem great for Analog GND and Digital GND connect together.

**Comment by charlespax** [comment]
These two issues are not pretty much the same https://github.com/PaxInstruments/t400-electronics/issues/59

**Comment by samchoy88** [comment]
Power distribution
![image](https://cloud.githubusercontent.com/assets/1327611/5891384/5833e8c4-a4cd-11e4-90c7-c7a1272733a9.png)

**Comment by samchoy88** [comment]
Isothermal plane connect to Normal GND by a short wire.

![image](https://cloud.githubusercontent.com/assets/1327611/5891980/21e10874-a4eb-11e4-9665-57c93009fb3d.png)
![image](https://cloud.githubusercontent.com/assets/1327611/5891985/5116748a-a4eb-11e4-9926-61d4149fb1e5.png)

**Comment by charlespax** [comment]
Cool. Closing issue.
