### ISSUE TITLE
Remove fiducials

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#125]
Maybe we should remove the fiducials on the T400 PCBs.

(From our discussion at lunch.)

**Comment by samchoy88** [comment]
The fiducials marks will be on the breakaway of the panel.

**Comment by charlespax** [comment]
Sounds good. Let's remove them in Electronics version 0.10.

**Comment by charlespax** [comment]
No fiducials on the current version in git. Closing issue.
![screen shot 2015-01-23 at 13 50 33](https://cloud.githubusercontent.com/assets/281642/5870366/ec9c6090-a306-11e4-8ee5-4b692f93770a.png)
