### ISSUE TITLE
Use smaller ICs

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#128]
Maybe we should move to small ICs.

(From our discussion at lunch.)

**Comment by samchoy88** [comment]
RTC smallest package is SO-8 which is currently use in Rev 0.9
ADC (MCP3424) currently using SO-14 <6x8.65mm>, we can switch to TSSOP-14 <6.4x5mm>
But switching smaller IC is not effective to reduce size in board. As the SD-card and RTC battery connector are too large compare with those IC.
May be we should back to issue RTC battery holder is large #1

**Comment by charlespax** [comment]
Agreed. Moving this to the "Electronics version :-)" milestone.

**Comment by charlespax** [comment]
Will not do. Closing issue.
