### ISSUE TITLE
Test pad size

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#129]
Maybe we should have larger test pads to aid in programming jig alignment.

(From our discussion at lunch.)

**Comment by samchoy88** [comment]
the programming port will apply larger pad that fit with SIM card connector:
![image](https://cloud.githubusercontent.com/assets/1327611/5609553/3c7ab97c-94de-11e4-8b99-db3fa644b8a6.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5609556/6d91413e-94de-11e4-98a2-fcfbc95bdc6e.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5609560/88e2f4a0-94de-11e4-920e-2db05a7fb40a.png)

**Comment by charlespax** [comment]
@samchoy88 what are your thoughts on this? We should have a decision for Electronics version 0.10.

**Comment by samchoy88** [comment]
Here is the drill size of the test pad.
![image](https://cloud.githubusercontent.com/assets/1327611/5890371/70a73054-a492-11e4-9257-b59348a6c280.png)

This is the reference test point component dimension:
![image](https://cloud.githubusercontent.com/assets/1327611/5890378/9231a042-a492-11e4-8ef9-984d789afa95.png)

http://www.keyelco.com/category.cfm/Test-Points-color-keyed-Thru-Hole-Mount/Compact-Style/p/518/id/521/c_id/746

**Comment by charlespax** [comment]
We only need a through hole test hook for a ground test point. The rest only need to be large enough to make contact with the test jig.

**Comment by samchoy88** [comment]
Here is the sample test pin on the Rev 0.9.
![image](https://cloud.githubusercontent.com/assets/1327611/5891497/d02922d0-a4d3-11e4-9e5e-879ffa21006b.png)

Mounting holes at the corner will handle all test point alignment.

**Comment by samchoy88** [comment]
Pogo pin work great on test point of Rev 0.9 board.
The pogo pin is sharp and narrow then the other (round head)
 
![image](https://cloud.githubusercontent.com/assets/1327611/5892210/bd7d27d0-a4f1-11e4-8fc9-8bbb80c19ac5.png)

**Comment by samchoy88** [comment]
Pogo pin reference:
http://www.pccp.com.tw/images/ccp/Tradition_Probes/P-25.pdf

**Comment by charlespax** [comment]
Okay, closing issue.
