### ISSUE TITLE
New soft power circuit

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#134]
I would like to implement the following soft power circuit and solve below issue:
- JP1 made circuit operate at 3.6V instead of 3.3V #117
- SW_PWR cannot detect button action #116

![image](https://cloud.githubusercontent.com/assets/1327611/5675391/11091f46-97f8-11e4-924f-4b9f8c0b3b4d.png)

I choose NAND gate instead of OR gate and made all input pulled up by 10K resistor.
![image](https://cloud.githubusercontent.com/assets/1327611/5675401/3b0cf754-97f8-11e4-985b-447b44c9f73a.png)

**Comment by charlespax** [comment]
My only concern is pullup resistor on PWR_ONOFF is drawing 0.33 mA while the device is just sitting there.

Here's what the power on sequence looks.
```
A   B   Y
H   H   L   <-- SW_PWR is not pressed, device is off. Device if off.
H   L   H   <-- SW_PWR is pressed, device is off. User presses and holds the power button.
L   L   H   <-- SW_PWR is pressed, device is on. Device boots up and enables power. User is still holding power button.
L   H   H   <-- SW_PWR is not pressed, device is on. User releases power button.
```

**Comment by samchoy88** [comment]
I think it can be 100K for pull up, as it only connect a logic which has high input impedance.

**Comment by charlespax** [comment]
Cool. Let's make that change in Electronics version 0.10.

**Comment by charlespax** [comment]
Done. Closing issue.
![screen shot 2015-01-17 at 02 09 17](https://cloud.githubusercontent.com/assets/281642/5781455/df528176-9ded-11e4-85c1-06696291da43.png)
