### ISSUE TITLE
Solar charging

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#136]
A Kickstarter community member suggests "Can you add some solar cells and use rechargeable batteries to allow long duration measurements and not having to worry about energy source."

**Comment by charlespax** [comment]
Solar charging would be cool. I think it would be best to have a system where the screen and device and be orientated for best usage while the solar panel can be placed in direct sunlight.

I think a solar powered battery pack connected to the microUSB port would be perfect for this.

![screen shot 2015-01-15 at 23 04 00](https://cloud.githubusercontent.com/assets/281642/5759755/d1a46dac-9d0a-11e4-94f2-fcc4ebbd4631.png)

Let's circle back to this idea in a future product.

**Comment by Tsillen** [comment]
The next product will probably have a more energy efficient design. Thus depending on the mode it is in it can increase battery life dramatically (several months to even a year of battery life).

**Comment by charlespax** [comment]
Especially if it doesn't have an LCD. Then we can integrate it all in one enclosure.

**Comment by Tsillen** [comment]
Even with a display. As you can electronically disconnect it completely with an mosfet. Thus making the power draw of the lcd pretty much zero.
