### ISSUE TITLE
LCD connector 1.0 mm footprint

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#137]
We need a footprint for an appropriate LCD connector for the LCD with a 1.0 mm pitch cable. The one in the image below should be good, but we need it to be 12 pins.

![screen shot 2015-01-16 at 14 35 46](https://cloud.githubusercontent.com/assets/281642/5772404/2a28ae84-9d8d-11e4-9751-c360d9b74bd4.png)

**Comment by samchoy88** [comment]
Original LCD it has 12 pins only.
However you are replacing the 16 pins 1mm Pitch connector.
Please kindly advice the signal assignment on new 16 pins 1mm Pitch connector connector.

![image](https://cloud.githubusercontent.com/assets/1327611/5798437/ff602c32-a001-11e4-9869-7916ec21c8cb.png)

**Comment by charlespax** [comment]
The connector is 12 pins. The 16 pin connector is a good template from which you can make a new connector.

**Comment by samchoy88** [comment]
OK, I follow this part number dimension for reference
P/N: FH12-12S-1SH

![image](https://cloud.githubusercontent.com/assets/1327611/5802210/c65dd6c4-a02d-11e4-9862-62954340106a.png)

**Comment by charlespax** [comment]
We have four samples of the new LCDs, so we'll have them for Electronics version 0.10. Moving to the Electronics version 0.10 milestone.

**Comment by samchoy88** [comment]
Both of the 1mm and 0.5 mm connector are in the PCB now.
See #140

**Comment by charlespax** [comment]
It's in Github. Closing issue.
![screen shot 2015-01-25 at 22 16 48](https://cloud.githubusercontent.com/assets/281642/5891714/e4b92be4-a4df-11e4-81cb-312f50ba1592.png)

**Comment by charlespax** [comment]
We should remove the 0.5 mm footprint when we have the custom LCD production run. See https://github.com/PaxInstruments/t400-electronics/issues/141.

**Comment by charlespax** [comment]
See also https://github.com/PaxInstruments/t400-electronics/issues/162
