### ISSUE TITLE
Adjust the thermal-couple connector width

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#138]
It seem the thermal couple connector is a little bit lose, 

![image](https://cloud.githubusercontent.com/assets/1327611/5779770/77165022-9de0-11e4-8b69-2c61e3fab8b1.png)

I try to reduce the distance between connector (+) and (-), around 11mm ~ 12mm.

![image](https://cloud.githubusercontent.com/assets/1327611/5779705/ecc6d9d2-9ddf-11e4-9fa9-659d4d050468.png)

**Comment by samchoy88** [comment]
See this improvement in Library
![image](https://cloud.githubusercontent.com/assets/1327611/5779978/05c3455e-9de2-11e4-92dd-9de31c09befa.png)

**Comment by charlespax** [comment]
For the male mini thermocouple connector we have (8 mm center-to-center) + (2.4 mm/2) + (3.17 mm/2) = 10.785 mm edge-to-edge. That is at least 1.11 mm of play side-to-side. And if we look at the Keystone connector there appears to already be enough extra room. @samchoy88 how do you feel about reducing that 12 mm to 10.75 or 11 mm?

![screen shot 2015-01-17 at 01 58 08](https://cloud.githubusercontent.com/assets/281642/5781291/61ee9c8e-9dec-11e4-8d65-33e0653c22ce.png)
![screen shot 2015-01-17 at 01 59 18](https://cloud.githubusercontent.com/assets/281642/5781320/96656eca-9dec-11e4-98a6-dfb29a692641.png)

And when you change the footprint make sure the centerline of the foot print meets the centerline of the male thermocouple connector. The blades are different widths, so there will be an offset.

**Comment by samchoy88** [comment]
As the thermal-couple has different size of terminal. (Positive pole is smaller then Negative pole).  Do you think we should apply the same size connector? (To avoid user plug in connector inversely)

![image](https://cloud.githubusercontent.com/assets/1327611/5798136/73b2ef00-9fff-11e4-9ce7-d08404cf79ef.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5779705/ecc6d9d2-9ddf-11e4-9fa9-659d4d050468.png)

Positive terminal: (3549 - For 0.110 tab) 
http://www.keyelco.com/product.cfm/Horizontal-Entry/Horizontal-Entry-Mini-Auto-Blade-Fuse-Clip/p/398/id/399/c_id/546/product_id/303

Negative terminal: (3572 - For 0.187 tab)
http://www.keyelco.com/product.cfm/Horizontal-Entry/3572/p/398/id/399/c_id/604/product_id/683

**Comment by charlespax** [comment]
No have will come from plugging in backwards. The top panel is keyed, so a user cant do it. However, there is no harm in using two different width connectors as long as they work. The small connectors I've tried tend to deform. If you have connectors that work, I'm open to trying them in the next board revision.

**Comment by samchoy88** [comment]
OK, I only apply the terminal: (3572 - For 0.187 tab)
http://www.keyelco.com/product.cfm/Horizontal-Entry/3572/p/398/id/399/c_id/604/product_id/683

![image](https://cloud.githubusercontent.com/assets/1327611/5799917/0256a176-a013-11e4-8483-4aac7eab49ab.png)


However, the connector width is 5.64mm, the minimum side to side (2 terminals) width is 11.4mm (connector touch together). I made the connector side to side 12.2mm, reserved 0.8mm margin for extension while tab inserted. 

![image](https://cloud.githubusercontent.com/assets/1327611/5801533/34ccc2ac-a027-11e4-9a15-f4fd5f278cf5.png)

**Comment by charlespax** [comment]
Looks good. Closing issue.
![screen shot 2015-01-25 at 22 20 39](https://cloud.githubusercontent.com/assets/281642/5891736/6abff998-a4e0-11e4-9b37-8fde65d5c8a9.png)

**Comment by samchoy88** [comment]
I just print it out and verify the board again.
Do you think the connector are too close together?
![image](https://cloud.githubusercontent.com/assets/1327611/5897029/f90afbd2-a579-11e4-80b1-a392dee08dd3.png)

**Comment by charlespax** [comment]
The connectors in Electronics version 0.10 will be fine as long as we can make a gap. We can put Kapton tape to ensure there is no electrical connection.

In Electronics version 0.11 we are moving to a custom connector (https://github.com/PaxInstruments/t400-electronics/issues/17), so this is not an issue we will face in production.
