### ISSUE TITLE
PCB mounting holes

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#139]
The PCB standoffs on the enclosure now have a shoulder to secure the PCB more firmly (https://github.com/PaxInstruments/t400-enclosure/issues/64). This requires enlarging the PCB mounting holes. The keepout area on the PCB is the same, so this should not require any change to the layout or routing.

**Comment by charlespax** [comment]
@starno What are the new dimensions of the PCB mounting hole?

**Comment by starno** [comment]
4.5mm diameter in the same location

![capture2](https://cloud.githubusercontent.com/assets/352025/5850856/d24fec36-a237-11e4-816e-ee09bb71e979.PNG)

**Comment by samchoy88** [comment]
Current mounting holes are 5.08mm diameter.
Is that OK?

![image](https://cloud.githubusercontent.com/assets/1327611/5890304/159bb93e-a490-11e4-9169-5bc55b98b3be.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5890308/4c05b9e8-a490-11e4-8438-8d11af8a2451.png)

**Comment by charlespax** [comment]
That screenshot shows a 2.54 mm hole. I don't understand.

**Comment by samchoy88** [comment]
Sorry, I made misunderstand on the value.
here is the corrected drill size
![image](https://cloud.githubusercontent.com/assets/1327611/5891873/9883ce7c-a4e5-11e4-8e2a-b8f1c4916a0a.png)

**Comment by charlespax** [comment]
Looks good. When we manufacture the PCB we'll have to make sure the holes are not plated, which would reduce their diameter. Closing issue.
