### ISSUE TITLE
Use smaller diodes

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#14]
Determine and implement the proper diodes.

**Comment by samchoy88** [comment]
I evaluate the LTC4412 suggested by Tsillen, it seem the cost is too high for the circuit. (around USD$2-3 for LTC4412)
Reference: http://www.newark.com/webapp/wcs/stores/servlet/Search?catalogId=15003&langId=-1&storeId=10194&gs=true&st=LTC4412

However, I also agree with him using using Mosfet to replace diode and extend battery life.
He suggested Switching Between Battery and External Power Sources by voltage supervision IC.
http://www.maximintegrated.com/en/app-notes/index.mvp/id/1136

A little bit cost for supervision IC (APX809-44SAG-7) around USD$0.2 http://www.mouser.com/ds/2/115/APX809_APX810-84245.pdf

It help to ensure USB side reach 4.38V and switch from battery power to USB power with delay and delay also avoid unstable/bouncing noise during USB start plug in.

**Comment by samchoy88** [comment]
Schottky Diode selection:
Part number: RB161M-20
Forward voltage: 0.28V @ 0.5A
Forward current: 1A
Package: SOD-123
http://www.mouser.com/ds/2/348/rb161m-20-210070.pdf

P-MOSFET selection:
Brand: DIODES
Part number: DMP2035U-7
Resistance Rds: 23mOhm
Continuous Drain Current: 3.6A
Package: SOT-23
http://www.mouser.com/ds/2/115/DMP2035U-464735.pdf

**Comment by samchoy88** [comment]
No decoupling cap required for supervision IC (APX809), as it needs fast response while VCC detect failure. The decoupling cap may filter the noise and less response to the VCC change.

The supervision IC has around 200ms delay to ensure the VCC voltage is stable and then switch OFF VBAT (/RST = HIGH). If any unstable voltage within that 200ms delay detected, supervision IC keeps switch ON VBAT (/RST = LOW).

If supervision IC detected VCC drop below Reset Threshold voltage, it switch ON VBAT (/RST = LOW) immediately which act similar to uninterruptible power supply (UPS).

![image](https://cloud.githubusercontent.com/assets/1327611/5681828/b61b1990-9856-11e4-8965-c50499a09673.png)

**Comment by charlespax** [comment]
This looks great to me. If you think we should do it, let's do it.

**Comment by samchoy88** [comment]
I think Tsillen suggested good improvement on charging circuit for T400.
Let's try in Rev 0.10.

**Comment by charlespax** [comment]
Awesome! Let's do it. Thanks, @Tsillen :-)

**Comment by charlespax** [comment]
Done.

![screen shot 2015-01-25 at 22 31 36](https://cloud.githubusercontent.com/assets/281642/5891798/f2beb356-a4e1-11e4-81b1-3cd00dcebb6f.png)
![screen shot 2015-01-25 at 22 31 27](https://cloud.githubusercontent.com/assets/281642/5891799/f2c6b290-a4e1-11e4-93db-e7fc70e776e4.png)
