### ISSUE TITLE
Two LCD connector footprints

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#140]
**NOTE: This is a nice-to-have feature, not a requirement. This feature is purely to aid testing and should not in any way compromise the production design.**

@samchoy88, if possible, it would be good to include both LCD connector footprints on the Electronics version 0.10 PCB. We only have four samples of the 1.0 mm pin pitch LCD, which would limit us to four active units for Electronics version 0.10. By including the second footprint we can have as many units as we like.

This is a quick and dirty illustration of what the PCB could look like. It would be best to not have the connector hanging off the board, but can if that's what it takes to get the footprint on there.
![screen shot 2015-01-23 at 13 33 18](https://cloud.githubusercontent.com/assets/281642/5870259/805adff8-a304-11e4-9a0f-f28b3443b4fd.png)

**Comment by charlespax** [comment]
If this doesn't work out for Electronics version 0.10, I can just roll an extended PCB that has the connector. This would be just for software development.

**Comment by samchoy88** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/1327611/5890285/431c2cdc-a48f-11e4-9c0d-20ae1407adff.png)

**Comment by charlespax** [comment]
Looks good. Closing issue. We should remove the 0.5 mm footprint when we have the custom LCD production run. See https://github.com/PaxInstruments/t400-electronics/issues/141.
![screen shot 2015-01-25 at 22 16 48](https://cloud.githubusercontent.com/assets/281642/5891747/8df505c0-a4e0-11e4-8a56-74046f53642b.png)
