### ISSUE TITLE
Remove unused 0.5 mm LCD connector

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#141]
In Electronics version 0.10 we kept the 0.5 mm and 1.0 mm LCD connector footprints for the transition from stock to custom LCD connector. Once we have the full  production run we can remove the 0.5 mm footprint.

See https://github.com/PaxInstruments/t400-electronics/issues/137

**Comment by samchoy88** [comment]
removed unused 0.5 mm LCD connector in PCB layout. and remaining 1mm LCD connector footprint.
![image](https://cloud.githubusercontent.com/assets/1327611/6652579/3c6ae096-caae-11e4-8d74-1bec64845fce.png)

**Comment by charlespax** [comment]
Perfect. I just got word that the new LCDs are in. We'll have plenty to work with.

**Comment by charlespax** [comment]
The LCD factory is shipping the LCDs today.

Looks done to me. Closing issue.
