### ISSUE TITLE
MicroSD card overhang

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#144]
The MicroSD card connector overhangs the PCB a little too much and interferes with the enclosure (https://github.com/PaxInstruments/t400-enclosure/issues/79). We need to bring it back a little bit.

**Comment by samchoy88** [comment]
Updated SD card position. The long side of the connector overhang to 0.7mm from the PCB edge
![image](https://cloud.githubusercontent.com/assets/1327611/6410772/f01642d8-beac-11e4-925c-fd6e120308bb.png)
