### ISSUE TITLE
MicroSD card footprint

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#145]
The MicroSD card connector does not match the component we have been prototyping with. We should make a new footprint that matches the component we will use in production.

The footprint should also indicate the centerline of the MicroSD card slot on the Measures layer.

**Comment by charlespax** [comment]
See also https://github.com/PaxInstruments/t400-electronics/issues/79. Make sure the card positions are correct.

**Comment by samchoy88** [comment]
According to the T-flash connect spec. I found Seedstuido library has slightly different on the pad.
![image](https://cloud.githubusercontent.com/assets/1327611/6652547/84f21d62-caad-11e4-95bc-62e170c18a44.png)


Below picture is the T-flash connector in Seedstuido library.
![image](https://cloud.githubusercontent.com/assets/1327611/6652541/265b7adc-caad-11e4-891e-39b8ed328d35.png)

The pin 4 should align to the line in below picture. And I updated component in Pax instrument library.
![image](https://cloud.githubusercontent.com/assets/1327611/6652545/62782632-caad-11e4-872c-5c9948d4a154.png)

**Comment by charlespax** [comment]
This change made it into the most recent board order, right? If so, we can close this and open another issue if it is still a problem.
