### ISSUE TITLE
Electronics version 0.10 assembly and testing

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#146]
Tests
- [x] Program bootloader at Arduino Lilypad USB
- [x] New Soft power circuit
- [x] New battery charging circuit
- [x] RTC
- [x] MCP9800 temperature sensor
- [x] LCD
- [x] SD card
- [x] SPI flash
- [x] Buttons
- [x] ADC

**Comment by samchoy88** [comment]
LCD test using U8g LCD library required to add following code:
at beginning - U8GLIB_PI13264 u8g(15, 16, 8, 4, 12);
In setup - u8g.setContrast(200);

**Comment by samchoy88** [comment]
Discovered SW_A always short to GND in a board.
Finally found out there is a short circuit under MCU (QFN package and hand soldering).

**Comment by samchoy88** [comment]
Experienced charging detected issue, please see:
Charging status unstable while No battery installed #147

**Comment by charlespax** [comment]
Old. Closing issue.
