### ISSUE TITLE
Charging status unstable while No battery installed

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#147]
MCU detected charging status unstable while no battery installed.
I check on the BATT_STAT test point seem stable at 2.5V but 3.4V at STAT pin of the charger IC.
May be the the voltage level is in marginal level and cause unstable.

**Comment by samchoy88** [comment]
Changed the resistor from 10K to 100K and it seem stable now.
![image](https://cloud.githubusercontent.com/assets/1327611/6075207/2670ae36-ae09-11e4-8937-f0916db80232.png)

**Comment by charlespax** [comment]
Based on a forum post I read (http://www.microchip.com/forums/m670010.aspx), we may need to add some capacitance on the battery terminals near the MCP73831. "I added another 4,7 µF ceramic capacitor, closer to the MCP73831 (right on the pins actually) and that seems to work too. So I guess it was some instability between the battery charger and the LDO."
![screen shot 2015-02-06 at 15 46 04](https://cloud.githubusercontent.com/assets/281642/6075944/4c485614-ae17-11e4-8222-3208888d08b9.png)

**Comment by samchoy88** [comment]
I found the battery disconnected made the charger IC not in Hi-Z status. It switch between Hi-Z and GND.

**Comment by samchoy88** [comment]
This issue is different from forum post (http://www.microchip.com/forums/m670010.aspx).
As it has problem with battery charger IC supply to LDO directly and causing unstable voltage supply to circuit.
But my problem is the STAT pin give unstable signal when No battery connected.

**Comment by samchoy88** [comment]
Fixed problem by this circuit. adding low pass filter and pull up resistor.
The 2k resistor and 10uF act as a low pass filter to avoid unstable signal from charging IC.
As I/O pin D5 do not have internal pull up resistor when act as an INPUT pin. A 10K resistor added externally.
![image](https://cloud.githubusercontent.com/assets/1327611/6077120/adddf758-ae26-11e4-9be6-131a7a736f36.png)

**Comment by charlespax** [comment]
Is there anything related to VBAT, VBAT_SENSE, or VBAT_EN floating that is causing this?

![screen shot 2015-02-06 at 17 30 31](https://cloud.githubusercontent.com/assets/281642/6077056/e1ca4720-ae25-11e4-84ea-e2553c13ce80.png)

![screen shot 2015-02-06 at 17 37 20](https://cloud.githubusercontent.com/assets/281642/6077140/dc5739dc-ae26-11e4-9caf-775ab65839a9.png)

**Comment by charlespax** [comment]
Okay, cool. When we're connected to USB the current drawn when STAT is low doesn't matter. When we are not connected to USB power STAT is Hi-Z, so the current draw should be negligible. Nice.

Can we close this issue?

**Comment by samchoy88** [comment]
Problem fixed.
