### ISSUE TITLE
Battery life time first test

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#149]
This is a first test on battery life time.

Reset RTC time before battery lifetime test. 

Below picture show the devices non-stop running for 23 hours and 38 minutes.
Here is the configure in software:
- No sleep and update LCD every 3 seconds
- LCD back-light always ON
- (1st Line) Read RTC
- (2nd Line) temperature sensor
- (3rd Line) 4 channels of ADC
- (4th Line) checking key press
- (5th line) Check battery charging status and analog reading of battery level

![image](https://cloud.githubusercontent.com/assets/1327611/6081129/24bc0696-ae52-11e4-9e4c-531222a69312.png)

**Comment by samchoy88** [comment]
No flash and SD card reading in this test

**Comment by charlespax** [comment]
Old. Closing issue.
