### ISSUE TITLE
SPI bus design

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#150]
I'm posting this application note about SPI bus design. I don't think we need this for the T400 thought. Moving to Ice box. http://hackaday.com/2014/11/25/better-spi-bus-design/

**Comment by samchoy88** [comment]
It looks great and better design to avoid unexpected failure on SPI bus.

**Comment by samchoy88** [comment]
![image](https://cloud.githubusercontent.com/assets/1327611/6652619/0bb3814a-cab0-11e4-89d2-0cd7e28d8128.png)

Here are the reference reason of this design.
1. Add Pullup Resistors for Chip Select & Reset Signals: 
Without a pullup resistor, the second device can "hear" and respond to the communication taking    place on the first device, if that second device's chip select pin is not pulled up.

2. Verify tri-state behavior on MISO: use a tri-state buffer chip if necessary.
Most SPI chips will tri-state (effectively disconnect) their MISO pin when their chip select signal is high (inactive). However, some chips do not have proper MISO tri-state behavior.

3. Protect bus access with SPI.beginTransaction(settings) and SPI.endTransaction().
Newer versions of Arduino's SPI library support transactions.  Transactions give you 2 benefits:
Your SPI settings are used, even if other devices use different settings
Your device gains exclusive use of the SPI bus.  Others will not disturb you.

**Comment by charlespax** [comment]
Will not do. Closing issue.
