### ISSUE TITLE
Silkscreen on ICSP header misleading

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-electronics#151]
The reset pin is labeled '3V3_EN', it should be 'RESET'

**Comment by charlespax** [comment]
Oh boy! Let's fix this in the next revision.

**Comment by samchoy88** [comment]
Corrected
![image](https://cloud.githubusercontent.com/assets/1327611/6409100/86bd5cd0-be99-11e4-82f3-312167a57c4d.png)
