### ISSUE TITLE
PCB locating feature

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#154]
We have introduced a PCB locating feature into the enclosure to aid the assembly process and secure the PCB. See https://github.com/PaxInstruments/t400-enclosure/issues/80

The PCB needs corresponding slots milled into the sides. @starno can you give @samchoy88 some dimensions for this?

**Comment by starno** [comment]
@samchoy88 the slots are symmetrical on the pcb.  the center on each slot is 15.28mm from the top edge of the PCB:
![screen shot 2015-02-27 at 12 04 14 pm](https://cloud.githubusercontent.com/assets/352025/6407343/132d7220-be79-11e4-83ad-67ad84a8b968.png)
and each slot is 2mm long and 0.9mm wide: 
![screen shot 2015-02-27 at 12 02 47 pm](https://cloud.githubusercontent.com/assets/352025/6407351/31f8751a-be79-11e4-98a9-04558bcb4dea.png)
The end of each slot is round matching the milling bit that cuts it.  I'd assume a 0.9mm round there.

**Comment by samchoy88** [comment]
Added slot on each side.
![image](https://cloud.githubusercontent.com/assets/1327611/6409280/21247b6c-be9c-11e4-8d27-498a880379cc.png)

**Comment by starno** [comment]
looks good

**Comment by charlespax** [comment]
Awesome! Let's close this.
