### ISSUE TITLE
Isothermal plane vias

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#157]
We have only a handful of vias thermally linking the top and bottom layers of the isothermal plane. I think we should have more. Maybe drop them on a 0.1 inch grid.

![screen shot 2015-02-25 at 18 16 06](https://cloud.githubusercontent.com/assets/281642/6368734/6d451ea8-bd1a-11e4-8636-d636a9d86e70.png)

**Comment by samchoy88** [comment]
More via added.
![image](https://cloud.githubusercontent.com/assets/1327611/6408734/04a5ac24-be95-11e4-949b-ba9c1a95ae37.png)

**Comment by charlespax** [comment]
Looks good. Closing issue.
