### ISSUE TITLE
Isothermal plane lateral heat transfer

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#158]
There are two traces on the bottom later going up to the MCP9800. These traces create a vertical cutout on the bottom layer of the isothermal plane. If we run these traces on the top layer as much as we can, we can get better thermal conductivity between the left and right sides.

![screen shot 2015-02-25 at 18 16 06](https://cloud.githubusercontent.com/assets/281642/6368771/d5b0ba92-bd1a-11e4-8562-275e880425fc.png)

**Comment by samchoy88** [comment]
Made these trace running on top layer now.
![image](https://cloud.githubusercontent.com/assets/1327611/6409012/69cc5ad2-be98-11e4-9efb-6e7b42842a01.png)

**Comment by charlespax** [comment]
Nice. Closing issue.
