### ISSUE TITLE
Battery charge controller

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#159]
Maybe we should change the MCP73831 or how the STAT is connected.

![screen shot 2015-03-19 at 13 49 46](https://cloud.githubusercontent.com/assets/281642/6725116/e4b01882-ce3e-11e4-9b40-45dc965de271.png)

**Comment by cibomahto** [comment]
MCP73832 has a open drain output, maybe we should use that one isntead

**Comment by cibomahto** [comment]
Otherewise there's a chance that VBUS_IN gets connected to STAT output through the MCP73831

**Comment by charlespax** [comment]
@samchoy88 this has been addressed, right?

**Comment by samchoy88** [comment]
Yes...this problem has been addressed....In Rev0.12 the board is using MCP73832T-2DCI/OT which is variance of MCP73831 with open drain output. But the circuit still keep Rev 0.12, as we can DNP or replace by 0 Ohm resistors.
