### ISSUE TITLE
MCP9800 part number

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#161]
We should specify which MCP9800 version we are using. It should be MCP9800A0 which gives and i2c address of 000. If we don't specify this, we may end up getting MCP9800A5, which has an address of 101.

![screen shot 2015-03-23 at 09 58 27](https://cloud.githubusercontent.com/assets/281642/6772898/4705636e-d143-11e4-8171-6c9df40aaad6.png)
![screen shot 2015-03-23 at 09 58 33](https://cloud.githubusercontent.com/assets/281642/6772901/4ba58908-d143-11e4-9b49-225bb08579c0.png)
![screen shot 2015-03-23 at 09 58 50](https://cloud.githubusercontent.com/assets/281642/6772902/4cb0d1d6-d143-11e4-988d-e431841e1b23.png)

**Comment by samchoy88** [comment]
Updated schematic.
Clearly mark down the part number in schematic and its relationship between I2C slave address.

![image](https://cloud.githubusercontent.com/assets/1327611/6985496/a58bb7a4-da66-11e4-99ed-9518a2f5e9fe.png)

**Comment by charlespax** [comment]
Great. Can we close this?
