### ISSUE TITLE
Battery polarity silkscreen

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#165]
In the next revision I would like the battery polarity to be silkscreened onto the PCB as in the image below.

![screen shot 2015-04-08 at 14 59 09](https://cloud.githubusercontent.com/assets/281642/7040323/492bac42-de00-11e4-85be-e85675c9661c.png)

**Comment by samchoy88** [comment]
Added silkscreen
![image](https://cloud.githubusercontent.com/assets/1327611/7230260/9304add0-e79e-11e4-8df3-fd0021fa06b5.png)
