### ISSUE TITLE
LCD connector solder paste layer

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#167]
The solder paste does not extend for the entire pad. Is this in purpose?

![screen shot 2015-04-16 at 19 02 42](https://cloud.githubusercontent.com/assets/281642/7179514/3e83491e-e46b-11e4-8ffb-5bf34afaa4ad.png)

**Comment by samchoy88** [comment]
It is a mistake while creating library.
This issue fixed in Rev 0.12
![image](https://cloud.githubusercontent.com/assets/1327611/7214139/843c84f6-e5cf-11e4-9270-47b3c894ca9a.png)
