### ISSUE TITLE
Update material list

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#168]
Update the attribute of each component on schematic except those resistors and capacitors.
Remaining 2 components has unknow part number or manufacturer.
- Unknow manufacturer of LG132643-DW
- Unknow manufacturer and Part no. of BL-5C battery connector

**Comment by charlespax** [comment]
The LCD is a custom manufactured part based on the LG132643-DW. You can list the manufacturer as Pax Instruments and the part number of PI132643FFDWHUV-P1

Did you get the battery connector part number from the guy in the HQB booth?

**Comment by samchoy88** [comment]
They only gave me the name of the connect in Chinese - "77电池座". And it is really common in market with the part number "BC-4-3P" for 3.0MM pitch 7.7MM 3P seat height of 77 Battery Battery Connector.
So, I will mark it in description as "Right angle battery connector, 3P, Pitch=3mm, 7.7mm height"
part number is "BC-4-3P"

**Comment by charlespax** [comment]
Is the material list finished? Can we close this?

**Comment by samchoy88** [comment]
Yes, all critical parts (except the common parts i.e resistors and capacitors) must have the following attribute:
1. MF (Manufacturer / Supplier / Brand)
2. MPN (Manufacturer Part number)
Additional note may provide in schematic. see below example:
![image](https://cloud.githubusercontent.com/assets/1327611/9178176/64d4be14-3fc8-11e5-99b5-5403b36bd432.png)

These attributes also exist in BOM list
![image](https://cloud.githubusercontent.com/assets/1327611/9178215/a6478b06-3fc8-11e5-9cd3-81eb4fc257f7.png)

**Comment by charlespax** [comment]
Done. Closing issue
