### ISSUE TITLE
MCU VBAT_SENSE on PD6 is not Analog Pin A10

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#169]
I got incorrect analog reading from analogRead(VBAT_SENSE);
I finally found the MCU component in schmatic created by sparkfun named the pin PD6 incorrectly.
someone posted the issue on Arduino forum and find the mistake too.
http://forum.arduino.cc/index.php?topic=82992.0
![image](https://cloud.githubusercontent.com/assets/1327611/7339024/8eee366e-ec92-11e4-9f08-a813dc21f792.png)

![image](https://cloud.githubusercontent.com/assets/1327611/7339026/a72f916e-ec92-11e4-84ae-68f5f7c1bc82.png)

**Comment by samchoy88** [comment]
Just required to correct the schematic of PD6 pin become D12/A11

**Comment by charlespax** [comment]
Did you change this in our part library and update the schematic and silkscreen?

**Comment by samchoy88** [comment]
Not yet change on schematic and silkscreen, please confirm to change

**Comment by charlespax** [comment]
Yes, please make our parts correct.

**Comment by samchoy88** [comment]
According to the pin assignment in pins_arduino.h.
![image](https://cloud.githubusercontent.com/assets/1327611/9173472/e31218b0-3fac-11e5-8c5b-cd6744c8fec7.png)

the part library corrected as follow:
Before:
![image](https://cloud.githubusercontent.com/assets/1327611/9173452/c092cafa-3fac-11e5-8619-c93893e7c91d.png)

After:
![image](https://cloud.githubusercontent.com/assets/1327611/9173526/5d604b46-3fad-11e5-84ff-d04047102a2e.png)
