### ISSUE TITLE
Custom thermocouple connector

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#17]
Create a custom thermocouple connector. The fuse connectors currently in the prototypes are not a long term solution. Something similar with a more flexible metal should work.

**Comment by charlespax** [comment]
It looks like we'll need a custom connector. Let's find a solution after sending out for Electronics version 0.10 boards. See https://github.com/PaxInstruments/t400-electronics/issues/92

**Comment by samchoy88** [comment]
Since you have tried the fuse clip from China market and reputable source like "Keystone".
And you experienced some mini thermocouple connectors are slightly different and larger ones will deform the connector such that slightly smaller connectors will then no longer fit snugly in the connector.

Custom connector:
![image](https://cloud.githubusercontent.com/assets/281642/5407300/e42d6398-81fd-11e4-84fd-8c2dd404ab37.png)

Keystone connector:
![image](https://cloud.githubusercontent.com/assets/1327611/5917381/f8b16b7a-a656-11e4-8c64-5e286074cfcf.png)


What is the key feature of custom thermocouple connector that made it become durable and will not deform by slightly larger thermocouple connectors?

**Comment by charlespax** [comment]
I don't know a key feature. We have to contact factories and see how they can help us.

**Comment by Tsillen** [comment]
Probably use something like spring steel. It will keep it's original shape unless you really brute force it.
It might be a better idea to skip the well known thermocouple connector and use another style of connector.

There are plenty low pin-count, long durability and reasonably priced industrial connector available.

**Comment by charlespax** [comment]
I'm moving this to the next mileston.

**Comment by charlespax** [comment]
Here is Tully's initial proposal:

![unnamed qq screenshot20150224143317](https://cloud.githubusercontent.com/assets/281642/6723014/d9e5ddf0-ce1c-11e4-9569-e18bab40cd93.png)
![unnamed qq screenshot20150224143356](https://cloud.githubusercontent.com/assets/281642/6723013/d99198f8-ce1c-11e4-995b-f8d97c6067e4.png)

**Comment by charlespax** [comment]
My response:

That looks great! I really like this concept :-) I have a few design
ideas we should talk about. I head back to the US Friday, so it would
be great to discuss before then. Today would be great.

Here’s some ideas I had. Just some brainstorming…
- Keyed. Front and back through hole parts can be different sizes, so the connector can be placed in only one orientation. Reduce worker mistakes. See attached
- Chamfered entry way. Small flange on the entry to help guide the male connector into place. Can also have flanges for both the horizontal and vertical. See attached.
- A second springy part at the entry way. Doesn’t have to be super strong. Just enough to keep the male blade flat against the connector.
- One spring tab each direction. This could address the ideas above. The male connector would be pressed down in two places. It could also act as a guide for the male blade contact. It would also make a keyed design obsolete.
- Packaging. I imagine these will be loose packaged and will be placed by hand for the first batch. It would be awesome if we could get these packaged on reels. Maybe we can include any features necessary for package the parts on reels and features for the pick and place machine.

![unnamed_qq_screenshot20150224143040](https://cloud.githubusercontent.com/assets/281642/6723044/4673b15e-ce1d-11e4-9c3b-97f9f46c847b.png)

I don't think the horizontal tabs are a good idea. They limit how close the connectors can be to each other. They are small and may be difficult to manufacture. The male thermocouple connectors already have rounding on their blade tips that would give the same effect.

Maybe we can make it such that a vertical wall extends the length of the connector. This could help prevent the male connector from moving side to side if twisted laterally.

Here is what the flat pattern could look like:
![blob1424857162350](https://cloud.githubusercontent.com/assets/281642/6723063/6147dae6-ce1d-11e4-8999-797d8a3e74a2.png)

When bent up it could look like this:
![unnamed_qq_screenshot20150224143356](https://cloud.githubusercontent.com/assets/281642/6723068/6c59f0ae-ce1d-11e4-810d-a373823afafe.png)

**Comment by charlespax** [comment]
Tully's response:

 made some changes to the design. I haven't thought about these changes very much yet. I will probably make a few more designs and send them all to the tooling company. Basically I need to go to bed and will think about this more.

![unnamed_qq_screenshot20150305043612](https://cloud.githubusercontent.com/assets/281642/6723087/9cb39930-ce1d-11e4-9c13-8f1acabcd1e4.png)
![unnamed_qq_screenshot20150305043544](https://cloud.githubusercontent.com/assets/281642/6723088/9cc6ab2e-ce1d-11e4-9229-67de86d3d02b.png)

**Comment by charlespax** [comment]
It would be nice if we could tighten up  width a bit. It really depends on the manufacturing tolerance of the connector. 3.3 mm would be good.
![screen shot 2015-03-19 at 09 11 17](https://cloud.githubusercontent.com/assets/281642/6723096/cddb0d54-ce1d-11e4-9408-33fd7107b93a.png)

The Omega mini thermocouple connector drawing give 3.17 mm for the largest male connector width. The connectors I have with me measure 3.1 mm and 3.14 mm.
![screen shot 2015-03-19 at 09 16 48](https://cloud.githubusercontent.com/assets/281642/6723103/d47813d2-ce1d-11e4-9447-2375f164ff87.png)

We will have to increase the interior height. The Omega specification gives 0.8 mm, but the connectors I have with me measure 0.92 mm and 1.0 mm. The main problem with the off-the-shelf connector we were using was that it would deform when the thicker male connectors were inserted. I want to avoid that here.
![screen shot 2015-03-19 at 09 26 05](https://cloud.githubusercontent.com/assets/281642/6723106/dd762082-ce1d-11e4-81ad-0b2ee9b432f9.png)

We need to make contact point much closer to the entrance. The Omega spec gives 12.7 mm as the terminal length, but the connectors I have are 10.4 mm and 10.8 mm.

Maybe we can reverse the insertion direction and extend the tab. This might give us the chamfered entrance and allow us to put the contact point closer to the entrance.
![screen shot 2015-03-19 at 09 35 05](https://cloud.githubusercontent.com/assets/281642/6723116/042c9bf2-ce1e-11e4-8452-92ff16324019.png)

We need to make contact point much closer to the entrance. The Omega spec gives 12.7 mm as the terminal length, but the connectors I have are 10.4 mm and 10.8 mm.

Maybe we can reverse the insertion direction and extend the tab. This might give us the chamfered entrance and allow us to put the contact point closer to the entrance.
![screen shot 2015-03-19 at 09 38 17](https://cloud.githubusercontent.com/assets/281642/6723119/0b8371fa-ce1e-11e4-9762-4948a96fcd7b.png)

**Comment by charlespax** [comment]
Here is the latest version of the clip. It's looking pretty sweet.
![screen shot 2015-03-24 at 20 07 54](https://cloud.githubusercontent.com/assets/281642/6801317/815645c8-d261-11e4-88fa-7cda978d7382.png)

**Comment by MLXXXp** [comment]
If the two contacts that bend upwards, when the pin slides under them, are springy enough to allow many insertions, do you think they will also end up distorting on the bends that join them to the sides?
![clip_bends](https://cloud.githubusercontent.com/assets/8151717/6801598/96825fde-d1ff-11e4-86b2-c65fc78cd125.png)

**Comment by MLXXXp** [comment]
I don't know if it's possible from a manufacturing standpoint, but perhaps reversing the design, so the split is on the bottom, would be better.

The blue splits become solid and the red is the new split.
![clip_reverese](https://cloud.githubusercontent.com/assets/8151717/6802026/36901036-d203-11e4-8815-089cf193f022.png)

**Comment by charlespax** [comment]
@MLXXXp I imagine the area I circled in green would flex a little, but it shouldn't flex any more than the area I have circled in blue. I think it wouldn't cause any problems, but I haven't done any FEA.

![screen shot 2015-03-24 at 20 17 52 copy](https://cloud.githubusercontent.com/assets/281642/6801785/019f1c74-d266-11e4-9a33-461113a0e66e.png)

**Comment by charlespax** [comment]
There may be a problem with how deep the connector inserts into the T400.

Here is the current connector version.
![screen shot 2015-03-24 at 20 17 52](https://cloud.githubusercontent.com/assets/281642/6802194/3f3abdba-d269-11e4-898d-1259aef41ba7.png)

The thermocouple would have to go a minimum of 5.7 mm into the connector to make contact. The shortest thermocouple connector I've seen is about 10 mm. Those numbers work well if the male part is fully inserted into the female part.
![screen shot 2015-03-24 at 20 18 54](https://cloud.githubusercontent.com/assets/281642/6802195/4162bdae-d269-11e4-9a38-c3bb5efe07d6.png)
![img_20150324_202229](https://cloud.githubusercontent.com/assets/281642/6802322/64d82e8a-d26a-11e4-8bd7-2adbc9487fc8.jpg)

For the T400 a male thermocouple connector must pass through the enclosure and a gap before it inserts into the female connector. In this image the black line marks off the point of contact.
![img_20150324_202212](https://cloud.githubusercontent.com/assets/281642/6802298/327aca4c-d26a-11e4-9eb1-d9100eba10c7.jpg)

We could have an indentation in the top panel, so the male connectors would only have to pass through the thickness of the enclosure. That would get the job done, but isn't the best contact and may not be very secure.
![img_20150324_202302](https://cloud.githubusercontent.com/assets/281642/6802345/991dd528-d26a-11e4-933c-70e29061ea5d.jpg)

We could remove the tab from the entrance of the connector and have two tabs on the sides. This would allow us to hang the connector over the edge and span the gap or part of the gap.
![screen shot 2015-03-24 at 20 54 48](https://cloud.githubusercontent.com/assets/281642/6802391/fe5edf9a-d26a-11e4-953f-4ad62ef41d49.png)
![screen shot 2015-03-24 at 20 54 41](https://cloud.githubusercontent.com/assets/281642/6802392/fe665270-d26a-11e4-9bb8-3881251a266d.png)

This would, however, cause some assembly problems when installing the top panel. I think we could overhang about 1.5 mm without causing problems. Perhaps a combination of wings on the sides and an indentation in the top panel is the solution.

**Comment by MLXXXp** [comment]
Why not (perhaps additionally) go with one of your earlier suggestions:

> Maybe we can reverse the insertion direction and extend the tab. This might give us the chamfered entrance and allow us to put the contact point closer to the entrance.

The current design lends itself to this.

**Comment by tully** [comment]
I made these models quickly so we can get pricing and know that the supplier can make them. Let me know what tweaking you think they need? These are the pictures I sent to the supplier.
![unnamed qq screenshot20150404063638](https://cloud.githubusercontent.com/assets/139140/6990022/5c072a2a-da96-11e4-99c2-8e5b15a407e0.png)
![unnamed qq screenshot20150404063658](https://cloud.githubusercontent.com/assets/139140/6990025/62c467e2-da96-11e4-9b96-391531c610f0.png)
![unnamed qq screenshot20150404063716](https://cloud.githubusercontent.com/assets/139140/6990027/67d9c5ba-da96-11e4-9c7f-8c06f3ca9a6b.png)

**Comment by charlespax** [comment]
Looks good. I think we'll have to tweak the 0.776 mm gap for the connector
since the Omega TC connector is specced at 0.8 mm. Can you do FEA on this?
If not, I'll get Nick in it.

**Comment by charlespax** [comment]
I've uploaded a Solidworks model from Tully's iges file. See tc-connector-5.sldprt.
![screen shot 2015-04-08 at 10 48 04](https://cloud.githubusercontent.com/assets/281642/7037912/c5263624-dddc-11e4-871a-ddea2b536b48.png)

**Comment by starno** [comment]
I modified the design until it deflected the appropriate amount given the desired plugin and removing forces.  The best performing shape looks like an e or a 9, thus E9.

![capture](https://cloud.githubusercontent.com/assets/352025/7317931/32c5019a-eab9-11e4-9669-02556b394c9e.PNG)

![capture2](https://cloud.githubusercontent.com/assets/352025/7317934/355ed782-eab9-11e4-854d-ba5e58ea0840.PNG)

Check out e35fd20581d6aff1ef34da704d4adacb0f3f28c7 on the enclosure branch

**Comment by charlespax** [comment]
Okay, we have a part that @starno and I think will work. The solidworks file can be downloaded directly from https://github.com/PaxInstruments/t400-enclosure/blob/master/Injection%20Molded/t400-thermo-clip2.SLDPRT?raw=true. I slightly modified the file to dimensionally constrain the flanges.

@tully if you think this is good, we can send it to the factory. I'd like to make a drawing or whatever the factory needs directly from the solidworks file rather than recreating it in another program. What do you need from me?

**Comment by charlespax** [comment]
I've added a drawing to the enclosure repository.
![screen shot 2015-04-29 at 16 22 00](https://cloud.githubusercontent.com/assets/281642/7386982/e76e7af6-ee8b-11e4-9c33-0d19a4eb6c7c.png)

**Comment by charlespax** [comment]
Here is the connector in the enclosure:
![capture2](https://cloud.githubusercontent.com/assets/352025/7448676/fb3ebb70-f252-11e4-9611-4bd0ac849135.PNG)

Maybe we should make the tab a little longer or at a different angle, so the male contacts don't intersect with the edge of the tab. @starno what do you think?

**Comment by starno** [comment]
Good catch, I didn't even notice that possibility.  I think making the hole smaller to avoid jamming on the upper tab is a good fix.

**Comment by charlespax** [comment]
I should have samples from the factory in two days.

**Comment by charlespax** [comment]
There has been some back and forth with the connector tooling. I had the factory make a few changes and received updated samples. They did a bad job with these samples and I'm working with them to improve.

Here are the images I sent to the factor to correct the issues. On the day they are manufactured I will be sitting at the machine at the factory checking parts. We must get this right.
![entry bend angle](https://cloud.githubusercontent.com/assets/281642/9108626/272d9ef0-3c62-11e5-89dd-87738d8bacbe.jpg)
![short edge angle](https://cloud.githubusercontent.com/assets/281642/9108627/27379a2c-3c62-11e5-996f-7ab3a8830df0.jpg)
![shoft edge shift](https://cloud.githubusercontent.com/assets/281642/9108628/273945ac-3c62-11e5-92c2-7f72b87a0553.jpg)
![long edge parallel](https://cloud.githubusercontent.com/assets/281642/9108629/273ff91a-3c62-11e5-8916-eb082d690b11.jpg)
![bottom parallel](https://cloud.githubusercontent.com/assets/281642/9108630/2744014a-3c62-11e5-8fec-81a5d920c0fd.jpg)

I put three footprints in the [Eagle library](https://github.com/PaxInstruments/PaxInstruments-Eagle-Libraries): a single contact, inside constraint, and outside constraint. The T400 will use the footprint constraining the male connector on the outside, the first image.
![img_20150803_165137](https://cloud.githubusercontent.com/assets/281642/9108575/ca4cd73c-3c61-11e5-90d3-e449f4b2b856.jpg)
![img_20150803_165125](https://cloud.githubusercontent.com/assets/281642/9108576/ca540e3a-3c61-11e5-9a57-5fc8ee741916.jpg)

**Comment by charlespax** [comment]
Now I'm just sorting out manufacturing issues. Finally closing this issue.
