### ISSUE TITLE
Thermocouple connector footprint

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#170]
We need a footprint for the thermocouple connector (https://github.com/PaxInstruments/t400-electronics/issues/17).

The connector should overhang the PCB a bit. @starno can you give dimensions for this? The PCB will need a slot for the vertical tab and a cutout for the 30 degree angled tab on the back.

This should go on the next revision.

Here is the part drawing.
![screen shot 2015-04-29 at 16 22 00](https://cloud.githubusercontent.com/assets/281642/7387045/8bc15fe2-ee8c-11e4-821e-afa2e4c83379.png)

**Comment by MLXXXp** [comment]
Should the cutout for the 30 degree angled tab be plated through and around, and exposed on the solder mask, to allow the tab to be soldered? This could give more mechanical strength to the clip to board bond.

**Comment by charlespax** [comment]
Here is a bottom view of the connector.
![screen shot 2015-04-29 at 19 24 40](https://cloud.githubusercontent.com/assets/281642/7389983/e57c5a5a-eea5-11e4-8b76-34b220821478.png)

I imagine the footprint in the image below. The vertical tab would be a milled slot that is plated through. The two slots for the 30 degree tabs would be milled and unplated. The area under the connector would be a solder pad, some of which would stick out a little from the connector to aid hand soldering.
![screen shot 2015-04-29 at 19 24 40 2](https://cloud.githubusercontent.com/assets/281642/7390022/4c1ff56e-eea6-11e4-95a7-79296e7a380f.png)

I don't think there would be any harm in plating the thirty degree slots, but I don't think they would be soldered in the SMD process. I think I would want that area clear of solder, so it doesn't interfere with the male connector. I think if someone hand soldered the thirty degree slot area from the bottom, it would be fine. Not really sure what's best.

**Comment by starno** [comment]
Ok, with the latest rev connector, a **1.5mm overhang** off the top edge of the PCB will give ~0.5mm clearance between the top panel and connector inlet.  
![capture3](https://cloud.githubusercontent.com/assets/352025/7448618/a7a7af72-f251-11e4-820e-057e627cafcc.PNG)
![capture2](https://cloud.githubusercontent.com/assets/352025/7448619/a8eecd34-f251-11e4-99cc-1eade6cab3fb.PNG)

Lets go with 1.5mm off the board.  (distance does not include the bent inlet portion)

**Comment by charlespax** [comment]
Here is a technical drawing. There should be enough information to make a footprint.
![e76e7af6-ee8b-11e4-9c33-0d19a4eb6c7c](https://cloud.githubusercontent.com/assets/281642/7449317/1e3231b2-f266-11e4-883e-9e8d2bca236b.png)

**Comment by samchoy88** [comment]
What is the part number of this clip?

**Comment by charlespax** [comment]
Manufacturer: Pax Instruments
Product number: 1024
Link: http://paxinstruments.com/products/sku1024/

**Comment by samchoy88** [comment]
1024 TC connector is ready in Pax instrument library
See https://github.com/PaxInstruments/PaxInstruments-Eagle-Libraries
Footprint locate In the PaxInstruments-Connectors.lbr

![image](https://cloud.githubusercontent.com/assets/1327611/8224778/fbcfd878-15be-11e5-814f-b8121adb9936.png)

Preview Footprint on T400 PCB.
![image](https://cloud.githubusercontent.com/assets/1327611/8224807/5460c7a4-15bf-11e5-9c55-464b913814d4.png)

**Comment by charlespax** [comment]
When I was on my phone I thought you used the old design files in the electronics repository. Now that I look at the first post of this issue I see the correct drawing. I think everything should be good then. I'll order these boards right away. Thanks, Sam.
