### ISSUE TITLE
Pax Instruments Eagle library

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#171]
We should move each part to the appropriate library in the Pax Instruments Eagle library repository (https://github.com/PaxInstruments/PaxInstruments-Eagle-Libraries)

**Comment by charlespax** [comment]
The SparkFun stuff should be moved into PaxInstruments-SparkFun.lrb, which has a description providing attribution to SparkFun. This will solve issue https://github.com/PaxInstruments/t400-electronics/issues/35.

All the other libraries are for parts created by Pax Instruments and are in the public domain.

**Comment by samchoy88** [comment]
Updated below library:
- Connectors
- Digital IC
- DiscreteSemi
- Electromechanical
- Power IC
- Boards
- Display
