### ISSUE TITLE
Fuse temperature

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#172]
The fuse gets pretty hot. We should select a different value such that any heat generated by the PTC fuse is negligible.

Revision 0.12 of the PCB was installed in the enclosure with a mostly discharged battery. After allowing the battery to charge for about thirty minutes I opened the enclosure and took several thermal images. The highest recorded temperature of the PTC fuse was 151 C.
![flir0080](https://cloud.githubusercontent.com/assets/281642/7409706/58e5f11c-ef5b-11e4-8df1-bf96eb39664c.jpg)

After letting the case sit open for a few minutes the temperature decreased to 132 C
![flir0092](https://cloud.githubusercontent.com/assets/281642/7409764/ce2e0ea0-ef5b-11e4-85ef-e237fc6a7817.jpg)

During this time the ADC was approximately 86 C. We should check to see how this temperature can affect the ADC readings.
![flir0084](https://cloud.githubusercontent.com/assets/281642/7409787/f0d67230-ef5b-11e4-9fe1-7641efff808f.jpg)

Even with the high temperature of the PTC the temperature across the isothermal plane was at a consistent 83.5 C. I believe this demonstrates the effectiveness of the thermal isolation slots and the thermal conductivity of the isothermal plane.
![flir0086](https://cloud.githubusercontent.com/assets/281642/7409788/f15fb9b4-ef5b-11e4-9d77-2dc8c202097c.jpg)
![flir0088](https://cloud.githubusercontent.com/assets/281642/7409789/f1bf8812-ef5b-11e4-84c4-49e36862b729.jpg)
![flir0090](https://cloud.githubusercontent.com/assets/281642/7409793/f35fa440-ef5b-11e4-8e83-609ad94055c0.jpg)
(Thermography is so cool!)

**Comment by samchoy88** [comment]
We are using MF-MSMF050 fuse in this circuit.
This is the specification of the fuse
http://www.mouser.com/ds/2/54/mfmsmf-72300.pdf
![image](https://cloud.githubusercontent.com/assets/1327611/7976478/21ead6aa-0aae-11e5-8435-e7eb9d217497.png)

It seem the resistance is relatively low 0.15Ohms ~ 1 Ohms.
When it is charging, it raise temperature to 151 Fahrenheit (66 Celcius).
If it is necessary to reduce the internal heat source, I recommend not to use fuse.
As all  PTC Resettable Fuses using similar technology to cut off circuit when temperature raise to certain level.

Besides, the Time to Trip is relatively long (around 1 second @ 2.5A current). Some of the components may damaged within that period.
That means the fuse protection may not effective.

![image](https://cloud.githubusercontent.com/assets/1327611/7976596/1903b62c-0ab0-11e5-9081-8706282ac3eb.png)

**Comment by charlespax** [comment]
Is it safe to remove the Fuse? If so, we should remove it.

**Comment by samchoy88** [comment]
I think we should remove it.

**Comment by charlespax** [comment]
Okay, let's remove it.

**Comment by samchoy88** [comment]
I think this case can be close after removed the fuse

**Comment by samchoy88** [comment]
Fuse removed in Rev 0.13
![image](https://cloud.githubusercontent.com/assets/1327611/9459791/11ed4520-4b32-11e5-88a8-93ce0d997ee9.png)
