### ISSUE TITLE
USB charging negotiation

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#176]
Is there anything that needs to be done to negotiate the USB charge rate?

**Comment by samchoy88** [comment]
It is possible to negotiate with USB host to get 2 Amps current (otherwise only 500mA available).
But it also made the charger IC and battery increase temperature rapidly.

**Comment by charlespax** [comment]
We can only do up to 500 mA.
![screen shot 2015-08-06 at 18 17 43](https://cloud.githubusercontent.com/assets/281642/9109349/8c66136a-3c67-11e5-9b2a-e0371a33d144.png)
