### ISSUE TITLE
RTC battery

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#178]
We need to select a battery part number for the RTC battery. We need to confirm it works with the electronics.

**Comment by samchoy88** [comment]
The following brand are the reliable brand/suppliers in Asia region.

Brand: GPI Int'l Ltd
http://www.gpbatteries.it/allegati/datasheet/specialistiche/litio/103123_CR1620.pdf

Brand: Maxell
http://www.maxell.com.tw/images/uploads/2014/10/CR1620_DataSheet_e.pdf

Brand: Panasonic
http://industrial.panasonic.com/lecs/www-data/pdf2/AAA4000/AAA4000CE45.pdf

**Comment by charlespax** [comment]
Please order samples of the batteries you think we should use.

**Comment by samchoy88** [comment]
Purchased some 1220 batteries and test and Currently testing below brand
Brand: Sony
Part number: CR1220
http://www.sony.net/Products/MicroBattery/cr/pdf/cr1220.pdf

Brand: Maxell
http://biz.maxell.com/files_etc/9/cr/en/CR1220_DataSheet_e.pdf

**Comment by charlespax** [comment]
Please add a note to the part that it takes a CR1220 battery.

**Comment by samchoy88** [comment]
Added note in schematic
![image](https://cloud.githubusercontent.com/assets/1327611/9517785/e36297dc-4ce4-11e5-811f-fac56b3842ba.png)
