### ISSUE TITLE
Thermocouple connector placement

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#179]
The thermocouple connectors must move closer to the top panel (https://github.com/PaxInstruments/t400-enclosure/issues/107). We could probably have the connectors hang over the PCB, but it would be best to extend the PCB top edge a little.

**Comment by samchoy88** [comment]
How much I can extend at the upper edge?

**Comment by charlespax** [comment]
You cannot extend the entire upper edge. About 70 mm to 74 mm of the top edge can be extended because it will have to fit inside the top panel recess as seen in the image below.
![screen shot 2015-08-09 at 16 03 51](https://cloud.githubusercontent.com/assets/281642/9154032/ae501228-3eb0-11e5-9b7e-7c82e107041e.png)

You can extend it between 2.5 to 2.75 mm as seen in this image.
![screen shot 2015-08-09 at 16 02 30](https://cloud.githubusercontent.com/assets/281642/9154034/ce338e62-3eb0-11e5-865e-c139b32f60bf.png)

**Comment by samchoy88** [comment]
Thermo-clip hang out a little bit (below 2.7mm), but I worry the clip and conflict with the LCD stand at both left and right side.
![image](https://cloud.githubusercontent.com/assets/1327611/9177822/493ab480-3fc6-11e5-8883-0efb3de2cc22.png)

**Comment by charlespax** [comment]
I will continue work on the connector footprint. I've looked at the spacing using the physical LCD, PCB, and connectors I have, so I'm 100% confident that we can make a footprint that works. I will make another test PCB that includes several versions of the this area of the T400 board, each with a different footprint. Let's hold off on ordering 0.13 PCBs until I can test the new thermocouple connectors on the new test PCB. The factory says we'll have new samples tomorrow. I'll make the test PCB today and order it for rush delivery. I should have it Thursday or Friday.

**Comment by charlespax** [comment]
I've updated the TC connector in the Eagle Library repo to tighten up the Dimensions. I checked it on the T400 PCB, but did not commit the changes. If this footprint works, it would look like this:
![screen shot 2015-08-11 at 19 52 58](https://cloud.githubusercontent.com/assets/281642/9196954/e6384d46-4062-11e5-841c-435d35582f34.png)

I've added another footprint test PCB to the repo to get the TC contacts as close as possible. We'll see which is best once we have the connectors this week and the test PCBs come in.
![screen shot 2015-08-11 at 19 33 38](https://cloud.githubusercontent.com/assets/281642/9196972/1c038fc6-4063-11e5-8fe8-d638af8b04da.png)

Don't worry about changing the TC connector on the T400 PCB right now. I'll let you know the results of the new test PCB. In the mean time you can continue work on the T400. Any changes to the footprint will be small and only have trivial, if any, affects on the layout.

**Comment by samchoy88** [comment]
Look better now.
![image](https://cloud.githubusercontent.com/assets/1327611/9229780/6635c886-4151-11e5-93aa-e613e7f2fad2.png)
