### ISSUE TITLE
Verify pin map

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#181]
Verify the pin map on the silkscreen matches the schematic.

**Comment by samchoy88** [comment]
![image](https://cloud.githubusercontent.com/assets/1327611/9459718/2f1ec73c-4b31-11e5-8ee2-a278aa9eca3f.png)
![image](https://cloud.githubusercontent.com/assets/1327611/9459767/aefc0d34-4b31-11e5-9d0e-a29d94bd9499.png)
