### ISSUE TITLE
Connect MCU VBUS pin to USB connector - VBUS_IN

### ISSUE THREAD

**Issue by samchoy88** [PaxInstruments/t400-electronics#183]
Firmware using VBUS pin on MCU to detect USB power supply connection status.
see below battery status defined in t400-firmware/t400/functions.h
![image](https://cloud.githubusercontent.com/assets/1327611/9178518/2d2e4e1a-3fca-11e5-80f2-bf93c5e17adf.png)

**Comment by charlespax** [comment]
Can we close this?

**Comment by samchoy88** [comment]
OK
