### ISSUE TITLE
Add 4.7k pulldown to VBUS input

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-electronics#188]
Unfortunately, when USB is disconnected and the device is powered from battery, there is a small amount of leakage through the battery charging circuit that leaves a residual voltage of 3.7V or so on the VUSB line. This prevents the VUSB input on the processor from being able to determine if the device is plugged in or not.

The most straightforward thing to do here is add a small pulldown resistor to bleed this current down. VUSB needs to be <1.4V for the processor to detect it as disconnected. Some quick experimentation shows that a 4.7k resistor drops the voltage to .37v, which means it creates a load of ~80uA on the battery at all times. Increasing the resistance to 11k raises the voltage to .8v but only drops the load to 72uA, so sticking with something around 4.7k is probably the best compromise between detection capability and battery life.
![screen shot 2015-08-14 at 6 14 36 pm](https://cloud.githubusercontent.com/assets/44493/9271939/5b513b3e-42b0-11e5-820d-f296c8ba08fc.png)
![screen shot 2015-08-14 at 6 15 23 pm](https://cloud.githubusercontent.com/assets/44493/9271987/ce41b4e8-42b0-11e5-8eca-4bfda5805e67.png)

**Comment by charlespax** [comment]
Version 0.13 has a 10k resistor. Change this to 4.7k.

![screen shot 2015-09-28 at 15 35 57](https://cloud.githubusercontent.com/assets/281642/10129994/bbb3c4ce-65f6-11e5-926c-dc8b538b5c86.png)
