### ISSUE TITLE
Procedure for modding V12 board to act like a V13 board

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-electronics#190]
This is required to test the latest firmware:
1. Add 4.7k resistor between VUSB and ground (#188)
2. Disconnect SW_B from PD3(INT3) and connect RTC_INT in its place (#186)
3. Disconnect RTC_INT from PE6(INT6) and connect SW_B in its place (#186)
4. Disonnect PWR_ONOFF from PB7 and connect to PD5 (#184)
5. Disconnect SW_PWR from PB0(SS) and connect to PB7 (#184)
6. Connect VUSB to net VBUS_IN (#183)
7. Not shown: Change R20 to 18.7K and R24 to 34K (#156)
8. Not shown: Add capacitor between VBAT_SENSE and ground (#156)
9. Optional: Remove R16, R15, R8, R11, R12 (pull-ups are enabled in firmware) (#189)

![dsc_4753](https://cloud.githubusercontent.com/assets/44493/9289192/fc60093a-4399-11e5-9429-7c769caca625.jpg)
![dsc_4757](https://cloud.githubusercontent.com/assets/44493/9289191/fc5f7ce0-4399-11e5-9142-d73fcbd482e9.jpg)

**Comment by cibomahto** [comment]
Original images were messed up
![dsc_4753](https://cloud.githubusercontent.com/assets/44493/9292345/781873ce-4425-11e5-966e-6a60c1d755d1.png)
![dsc_4757](https://cloud.githubusercontent.com/assets/44493/9292346/786b8d34-4425-11e5-80eb-1a3d02aa6d30.png)

**Comment by charlespax** [comment]
In step 2, SW_B is actually connected to PD2(INT2). This is in the schematic, the picture you uploaded, and the datasheet.
![screen shot 2015-10-03 at 18 28 04](https://cloud.githubusercontent.com/assets/281642/10262495/826b6c6c-69fc-11e5-88bc-453f50274001.png)
![screen shot 2015-10-03 at 18 30 01](https://cloud.githubusercontent.com/assets/281642/10262502/d296722c-69fc-11e5-94b5-d191b1b2d688.png)

To correct step 2, 2. RTC_INT will be connected to PD2(INT2) and SW_B will be connected to PE6(INT6).

**Comment by cibomahto** [comment]
Ok, that sounds correct.
