### ISSUE TITLE
DPN pull-up resisors

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#191]
The firmware enables the 32u4 internal pullup resistors. We should DNP R16, R15, R8, R11, R12 in production.
See https://github.com/PaxInstruments/t400-electronics/issues/189#issuecomment-131687633

**Comment by samchoy88** [comment]
Added "Populate" attribute in pull-up resistor, this will show in BOM list
![image](https://cloud.githubusercontent.com/assets/1327611/9323233/edaf6c6e-45b0-11e5-962d-bd04b1e5073e.png)
