### ISSUE TITLE
Vias under thermocouple connectors

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#193]
I'm concerned about the vias under the thermocouple connectors. We are using tented vias, but if there is an error or if we switch to untended vias, there could be a short. I would like to remove the four vias under the connectors.

![screen shot 2015-08-26 at 17 28 32](https://cloud.githubusercontent.com/assets/281642/9490107/51ed320c-4c18-11e5-9eb7-dea8dcb222d1.png)

**Comment by samchoy88** [comment]
Removed Via under connector
![image](https://cloud.githubusercontent.com/assets/1327611/9517813/0cac1514-4ce5-11e5-81ac-d437073912a9.png)

**Comment by charlespax** [comment]
This has not been committed to github. Reopening.
