### ISSUE TITLE
Traces through LCD slots

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#194]
There are some traces going through or too close to the slots the LCD clips into. These should be moved.

![screen shot 2015-08-26 at 17 36 51](https://cloud.githubusercontent.com/assets/281642/9490398/170920cc-4c1a-11e5-97bc-8f10a1f6d106.png)
![screen shot 2015-08-26 at 17 37 11](https://cloud.githubusercontent.com/assets/281642/9490400/1952a614-4c1a-11e5-99ae-22136db4fa03.png)

**Comment by samchoy88** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/1327611/9574035/3e0eb8f6-4ff5-11e5-95c6-11f58b801d10.png)
![image](https://cloud.githubusercontent.com/assets/1327611/9574039/53e2da9a-4ff5-11e5-953b-573f76dfe298.png)

**Comment by charlespax** [comment]
This has not been committed to github. Reopening.

**Comment by samchoy88** [comment]
Yes, generate Gerber file to make sample
