### ISSUE TITLE
Silkscreen overlap

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#195]
The thermocouple channel labels are cutoff by some components. These can be moved a up a little.
![screen shot 2015-08-26 at 17 41 21](https://cloud.githubusercontent.com/assets/281642/9490370/ec45b814-4c19-11e5-93b6-cd66c52f96fa.png)

**Comment by samchoy88** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/1327611/9573995/e0f17e7e-4ff4-11e5-838e-066e4478072a.png)
