### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#196]
Please update to the square logo in the Aesthetics library, 0.5 inch if it fits, but 0.25 inch is fine too.

![screen shot 2015-08-26 at 17 48 55](https://cloud.githubusercontent.com/assets/281642/9490485/ccb5fb02-4c1a-11e5-8f51-e321875061ec.png)
![screen shot 2015-08-26 at 17 49 46](https://cloud.githubusercontent.com/assets/281642/9490502/ddd1af8a-4c1a-11e5-8c2c-6d51c8305179.png)

**Comment by samchoy88** [comment]
Updated
![image](https://cloud.githubusercontent.com/assets/1327611/9574016/17151aec-4ff5-11e5-933d-48a7b12348b5.png)

**Comment by charlespax** [comment]
This has not been committed to github. Reopening.
