### ISSUE TITLE
Buttons are swapped

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#198]
The version 0.13 PCB I have differs from the modified 0.12 board (https://github.com/PaxInstruments/t400-electronics/issues/190). The record buttons appears to be swapped with the interval button.

**Comment by charlespax** [comment]
This seems to be fine. I made a note in the t400.h pin definitions on which pins to switch between 0.12-mod and 0.13.

**Comment by cibomahto** [comment]
This seems fine. The INT6 input is goofy but the workaround should be effective either way.
