### ISSUE TITLE
MCP73831 Note

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#219]
Make sure the MCP73831 is specified in the schematic and BoM. Otherwise, there would be charge problems.

**Comment by slowcoder** [comment]
That would probably be which version of the MCP73831 you intend to be used. The different MCP73831-X chips have different CC->CV thresholds (4.2V, 4.35V, etc)

**Comment by samchoy88** [comment]
The exactly part number should be in Eagle schematic
The part number is MCP73832T-2DCI/OT
![image](https://cloud.githubusercontent.com/assets/1327611/21074767/f34ddd26-bf3b-11e6-80aa-57bbda394f05.png)

![image](https://cloud.githubusercontent.com/assets/1327611/21074778/3e3aedce-bf3c-11e6-96e3-edc6c250236f.png)

**Comment by charlespax** [comment]
I've updated the library device and labwiz schematic to "MCP73831/2"

![screen shot 2016-12-11 at 12 34 41](https://cloud.githubusercontent.com/assets/281642/21078350/5c2fc7c0-bf9e-11e6-93ad-4693e18b5038.png)
