### ISSUE TITLE
Pax Instruments logo missing

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#27]
Fix: Add the new scope logo.

**Comment by samchoy88** [comment]
This logo should put on PCB?
![image](https://cloud.githubusercontent.com/assets/1327611/5645154/e7c4ce66-96a6-11e4-915a-293c62d934a4.png)

**Comment by charlespax** [comment]
Oh no! That's not the logo. I need to get you a proper SVG image.

This is the logo.
![screen shot 2015-01-08 at 01 41 14](https://cloud.githubusercontent.com/assets/281642/5650228/7f67dcf6-96d7-11e4-8ad5-f180e90babda.png)

**Comment by samchoy88** [comment]
Do you have higher resolution logo?

I am going to import in PCB, I made the logo from 
![image](https://cloud.githubusercontent.com/assets/281642/5650228/7f67dcf6-96d7-11e4-8ad5-f180e90babda.png)

The logo look like below.
![image](https://cloud.githubusercontent.com/assets/1327611/5890216/0840a8ca-a48c-11e4-995a-9c52337a139e.png)

**Comment by charlespax** [comment]
I've added t400-electronics/graphics/ which contains the logo in raster and vector formats.

**Comment by samchoy88** [comment]
I made the logo with size 270x270 mil.
it locate at bottom side near battery holder.
![image](https://cloud.githubusercontent.com/assets/1327611/5891434/6ede0750-a4d0-11e4-9bb6-f2b8ef78acba.png)

**Comment by charlespax** [comment]
It's in Github. Closing issue.
![screen shot 2015-01-25 at 22 28 53](https://cloud.githubusercontent.com/assets/281642/5891791/90d2deb0-a4e1-11e4-9347-136378007b45.png)
