### ISSUE TITLE
What test points are needed?

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#37]
There are test points on the thermocouple pads. Where else should they be? This is needed for any test fixture that is made for production.

**Comment by samchoy88** [comment]
Currently at Rev 0.9 has following test point:
-GND
-3.3V
-VBUS
-USBVCC
-VBUS_IN
-VBAT

But I think we need more test point and verify following signal:
- BATT_STAT
- VBAT_SENSE
- VBAT_EN
-3V3EN

**Comment by samchoy88** [comment]
Test point list in Rev 0.10:
- 3.3V
- GND
- VBAT_SENSE
- LCD_BL
- BATT_STAT
- VBUS_IN
- VBAT
- SD_CS
- FLASH_CS
- SW_PWR
- PWR_ON/OFF
- USBVCC
- VBUS

![image](https://cloud.githubusercontent.com/assets/1327611/5892001/2583d24e-a4ec-11e4-81bf-3990b9f2596a.png)

**Comment by samchoy88** [comment]
Added ISOTHERMAL GND test point to make sure it connected to normal GND.

![image](https://cloud.githubusercontent.com/assets/1327611/5892055/ca97f0ca-a4ed-11e4-8ac8-8d9c2e3ff2a2.png)

**Comment by charlespax** [comment]
I think we can close this out. If we need other points for the test jig, we'll have to open other issues.
