### ISSUE TITLE
What are the effects of input voltage on the 32u4 internal reference voltage?

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#43]

**Comment by samchoy88** [comment]
I double check on Atmega32u4 datasheet.
It seem we connected the AREF to 3.3V of the regulator. It means the MCU ADC conversion is base on 3.3V as reference voltage.
Otherwise, I should connect the AREF to a filter capacitor only and software required to set register using 2.56 internal reference.
![image](https://cloud.githubusercontent.com/assets/1327611/5643369/a759fe50-9692-11e4-98db-ec3765e0099f.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5643432/7c9d0b98-9693-11e4-8417-7d277e2edd3b.png)

Should I disconnect the AREF to 3.3V?

**Comment by charlespax** [comment]
I was incorrect in my understanding that the AREF is different from the 2.56 V internal reference and they can be used independently. It seems we can select between INTERNAL or AVcc in software. That's probably better than AVcc being hard-wired to VREF. I think you're right and we should hook AREF to a capacitor. @cibomahto what do you think? It affects the software, so I don't want to make a change unless you give the okay.

![screen shot 2015-01-15 at 23 51 00](https://cloud.githubusercontent.com/assets/281642/5760691/6f4e5274-9d11-11e4-945b-0aa1e61abb68.png)



The idea on the table is to use the internal 2.56 V internal reference to partially calibrate the AREF value. From further reading I see that it will not make things generally more accurate. See http://www.skillbank.co.uk/arduino/measure.htm and http://www.re-innovation.co.uk/web12/index.php/en/information/electronics-information/accurate-voltage-measurement

However, the internal 2.56 V internal voltage reference may be useful as a reference for measuring the battery voltage as the battery voltage drops below approximately 3.5 V. As the battery voltage decreases the MIC5219 output voltage will be affected. The problem is that the battery voltage affects the reference voltage from which we are measuring the battery voltage.

MIC5219 output V versus input V:
![screen shot 2015-01-15 at 23 46 25](https://cloud.githubusercontent.com/assets/281642/5760607/e99d9a04-9d10-11e4-9b8c-11a4769d63e0.png)

**Comment by samchoy88** [comment]
Do you want me disconnect 3.3V from ARef pin and use internal 2.56V reference?

This is Rev 0.8 connection:
![image](https://cloud.githubusercontent.com/assets/1327611/5802422/ee6b674c-a02f-11e4-910b-5a6a89d8c978.png)

**Comment by charlespax** [comment]
Yeah, let's do it and add the bypass cap.

**Comment by charlespax** [comment]
Here is the issue to address this int he firmware: https://github.com/PaxInstruments/t400-firmware/issues/21

**Comment by samchoy88** [comment]
Disconnected to 3.3V
![image](https://cloud.githubusercontent.com/assets/1327611/5891939/31270d58-a4e9-11e4-9f72-966264677e27.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5891944/46cc120c-a4e9-11e4-810e-1e7e33a73647.png)

**Comment by charlespax** [comment]
Nice. Closing issue.

**Comment by samchoy88** [comment]
In Rev 0.10, the ARef Pin measured 2.508V while software selected internal voltage reference.
However, the ARef Pin measured 3.269V while software selected default voltage reference.
It seem the internal voltage reference has high tolerance then using default voltage reference.

**Comment by charlespax** [comment]
@samchoy88 I don't understand what you mean. The internal voltage reference of the ATmega32U4 has a 2.56 V nominal voltage.

**Comment by samchoy88** [comment]
As the Reference voltage is critical for calculating the VBAT voltage value.
I expect using internal 2.56V voltage reference. and calculate the VBAT level by ADC x 2.56V / 1023.
However, I found the VBAT value does not match with measuring point.

After checking the circuit and ARef pin, the internal voltage reference only supply 2.508V and causing incorrect result in calculation.
