### ISSUE TITLE
Properly ground isothermal plane

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#59]
Review the grounding on the isothermal plane. The thermocouple filtration links to it.

**Comment by samchoy88** [comment]
The PCB design should have better planning and avoid noise affecting ADC.
It may require to place the regulator in better position.
![image](https://cloud.githubusercontent.com/assets/1327611/5644205/067a0796-969c-11e4-89a2-6dcc9168dea1.png)

Reference: http://www.silabs.com/Support%20Documents/TechnicalDocs/an203.pdf

**Comment by charlespax** [comment]
In addition to regulator placement should be be isolating GND and ISOTHERMAL with a resistor, inductor, both, something else, or nothing at all?

**Comment by samchoy88** [comment]
It seem the Analog ground and Digital ground connected by 0 Ohm resistor.
But the resistor should place nearby Power supply and close to device with mixed signal.

**Comment by charlespax** [comment]
These two issues are not pretty much the same https://github.com/PaxInstruments/t400-electronics/issues/123.

**Comment by charlespax** [comment]
Done. Closing issue.
