### ISSUE TITLE
Add both QFN and TQFP footprints for the 32u4

### ISSUE THREAD

**Issue by mhenstell** [PaxInstruments/t400-electronics#68]
32u4's are hard to source for some reason, adding both footprints gives you some flexibility in component sourcing.

**Comment by samchoy88** [comment]
per our discussion at lunch, here are the stock and price of ATmega32U4 in most distributors.
Reference link: https://octopart.com/partsearch#!?q=ATmega32U4

ATmega32U4-AU = TQFP package
Atmega32U4-MU = QFN package
![image](https://cloud.githubusercontent.com/assets/1327611/5658307/af93114e-973a-11e4-9393-81c443e0aad4.png)

![image](https://cloud.githubusercontent.com/assets/1327611/5658319/d1f846a0-973a-11e4-9e2c-00d8575d0978.png)

**Comment by charlespax** [comment]
Nice! It looks like we can kill the QTFP footprint as the QFN package will be available enough for us.

**Comment by samchoy88** [comment]
Updated board components placement in Rev 0.10. More space are allow for TQFP package.

![image](https://cloud.githubusercontent.com/assets/1327611/5853763/aeefa630-a261-11e4-9405-eee05bd53bf9.png)

**Comment by charlespax** [comment]
Beautiful!

**Comment by charlespax** [comment]
This was implemented in Electronics version 0.10. Moving to that milestone.
