### ISSUE TITLE
Battery charging and consumption

### ISSUE THREAD

**Issue by Tsillen** [PaxInstruments/t400-electronics#71]
What happens when the usb is connected and the battery is charging while the device is on?
I did some simulations in LTSPICE.

When using a generic diode you consume around 390mW (500mA load) in diode D2 (see pax sch).
PIC : http://imgur.com/A0nauZE
![a0nauze](https://cloud.githubusercontent.com/assets/281642/4192980/a460497e-379d-11e4-8732-134f1564c156.png)

I looked in your design and I saw you use a schottky diode to lower the thermal effect.
So I went to LTSPICE again and used an generic schottky diode Diodes inc. B560C (~ the same specs as the one you chose). And i ran the simulation again. Now the consumption is dramatically lowered but still 191mW of heat (500mA load). 
PIC: http://imgur.com/yfGBdWy
![yfgbdwy](https://cloud.githubusercontent.com/assets/281642/4192992/c3e25dbe-379d-11e4-8c90-1c15f72e7fb4.png)

Because i'm going to have the same issue in my OpenBL-5C project (see my github) I went and looked for an solution.

What came up in my mind is to use some mosfets. When the USB is plugged in one mosfet goes in on mode thus running the rest of the circuit of the 5V from the usb. A second mosfet is then activated to break the connection between the battery and the 3.3V regulator.
To make this more clear see pic:

I tried a circuit with an pmos and an nmos but it wasn't an success. Another solution would be to use 2 comperators, the first one is high when the usb is connected, the second one is used to invert the low signal (when usb is not connected) to an high signal so simple and inexpensive n channel mosfets can be used. But this is quite complicated...

So I went on google and i found a chip that does it for you :
http://www.maximintegrated.com/en/app-notes/index.mvp/id/1136
or:
http://www.linear.com/product/LTC4412

If something like this is implemented in the design the battery life will be improved slightly and maybe even the measuring accuracy (everything that heats inside the case effects the accuracy).

I hope this can help you improve the design.

**Comment by charlespax** [comment]
I believe this is addressed in Electronics version 0.10. Closing issue.
![screen shot 2015-01-25 at 17 42 41](https://cloud.githubusercontent.com/assets/281642/5891050/a168df22-a4b9-11e4-89a3-5fffa172d104.png)
