### ISSUE TITLE
Leakage current in battery Vbat_EN circuit

### ISSUE THREAD

**Issue by Tsillen** [PaxInstruments/t400-electronics#74]
The Vbat_en pin is (i assume) used to enable the measuring of the battery voltage.
When a microcontroller pin is low it is not 0V or (GND) but somewhere around 0.4 - 0.7V .
When the battery is at 3.7V and vbat_EN pin is low. There is a leakage current of ~120uA.
![leak1](https://cloud.githubusercontent.com/assets/8618634/4192838/f4637cf4-379b-11e4-9867-30736d454c18.png)

The same goes for when the Vbat_en pin is high. It is around micro vcc +0.5V.
This has a leakage current of -60uA worst case.
![leak2](https://cloud.githubusercontent.com/assets/8618634/4192842/fa84cb92-379b-11e4-8dd9-49c4ac532bf9.png)

One could fix this by using a logic level mosfet to enable / disable the voltage measurement.

**Comment by charlespax** [comment]
The Atmega32U4 datasheet indicates the I/O input leakage current is 1 uA. This is fine. Closing issue.

![screen shot 2015-01-25 at 17 51 09](https://cloud.githubusercontent.com/assets/281642/5891069/d57b880e-a4ba-11e4-9de9-d7e29c69af53.png)
