### ISSUE TITLE
Micro SD card does not reach enclosure edge

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#79]
The SD card should be at the enclosure edge when it is inserted. We will probably need a new connector.

**Comment by starno** [comment]
I decided to change the overhang to 0.7mm from the PCB edge.  The long side of the connector was cutting it a little too close to the enclosure edge.

0.79mm:
![screen shot 2015-01-03 at 3 19 54 am](https://cloud.githubusercontent.com/assets/352025/5598904/ed4999fe-92f8-11e4-8f33-e48770f2c082.png)

0.7mm:
![screen shot 2015-01-03 at 3 28 54 am](https://cloud.githubusercontent.com/assets/352025/5598906/f43b4744-92f8-11e4-9a61-00a4b07609a6.png)

**Comment by charlespax** [comment]
Good call. I can see it's a bit close in the SLA print.

**Comment by samchoy88** [comment]
I have a little bit confuse on the SD card hang out distance.
Current the Card lock position is at 3.64mm away from the side of PCB.
![image](https://cloud.githubusercontent.com/assets/1327611/5525584/60a2d6c4-8a23-11e4-9cdf-1bb628685e7b.png)

**Comment by charlespax** [comment]
@samchoy88 you are correct. The topic of this issue is the clearance between the inside of the enclosure and the Sd card slot. They were a little too close.

**Comment by charlespax** [comment]
I think this is solved in Electronics version 0.10. Let's revisit it in Electronics version 0.11 if it's a problem. See the footprint verification issue (https://github.com/PaxInstruments/t400-electronics/issues/145). Closing issue.
