### ISSUE TITLE
Align 2x3 headers and enclosure cutouts

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#97]
For history see https://github.com/PaxInstruments/t400-electronics/issues/86.

**Comment by charlespax** [comment]
I think there is a good spot for the headers to go. In the Enclosure version 0.1 (SLA) print I cut out the cutout and continued cutting to the wall at the top of that area.

You can see i this image where a connected header cable could sit.
![img_20150103_210735](https://cloud.githubusercontent.com/assets/281642/5602519/bcf238e8-938d-11e4-8a50-97e167ca6e6c.jpg)

And here is the header seated on the board in that same spot inside the enclosure.
![img_20150103_210807](https://cloud.githubusercontent.com/assets/281642/5602521/d0048788-938d-11e4-8bef-12c198dd0473.jpg)

And here is the header on the board without the enclosure back.
![img_20150103_210828](https://cloud.githubusercontent.com/assets/281642/5602523/df005212-938d-11e4-954a-4e1f3cf14759.jpg)

I think we would be okay if we moved the thermal isolation slots a bit.

**Comment by samchoy88** [comment]
Please advice the location of the connector on the PCB.

From the image I estimated the location of the connector, It seem a little bit difficult to move thermal isolation slots a bit, as the slot and the component at top side around 1mm distance. It is not suggest to place component too close to the slot.
![image](https://cloud.githubusercontent.com/assets/1327611/5614918/cfa08856-9530-11e4-8483-657ae2c7b203.png)

**Comment by charlespax** [comment]
Can we move that component?

**Comment by samchoy88** [comment]
Those components are thermocouple circuit, it has little bit space to move inside.

![image](https://cloud.githubusercontent.com/assets/1327611/5664414/57073a54-978b-11e4-9540-a69f36230ccd.png)

**Comment by charlespax** [comment]
Cool. Please nudge things around, so we can move the slot and get the header in there.

**Comment by samchoy88** [comment]
After I fixed the issue - Longer soler pads on 2x3 header footprint #122. The footprint pad size is larger than the component. the header cannot place on the position/orientation suggested by @charlespax.
- Horizontal orientation made not enough space for the signal to the header
- Separation between thermal-couple are fixed and not recommend to move. This made the slot can move very limited distance. (see below pictures)
![image](https://cloud.githubusercontent.com/assets/1327611/5761198/cddc69ea-9d14-11e4-8efc-89a1dab9e260.png)

![img_20150103_210828](https://cloud.githubusercontent.com/assets/281642/5602523/df005212-938d-11e4-954a-4e1f3cf14759.jpg)

**Comment by charlespax** [comment]
It sounds like a feature we chose for the test rig is affecting the T400 design in a negative way. Any compromise that needs to be done should happen in the test rig. Rather than using the SIM connector we can figure our something else like individual spring contacts.

@samchoy88 can you place the 2x3 header in the desired location if we went back to the original footprint?

**Comment by samchoy88** [comment]
Header position updated in Rev 0.10(unit = mm)
![image](https://cloud.githubusercontent.com/assets/1327611/5891579/6b23e61c-a4d9-11e4-96b4-5befee44649c.png)

**Comment by charlespax** [comment]
Cool. Closing issu.e

![screen shot 2015-01-25 at 22 25 47](https://cloud.githubusercontent.com/assets/281642/5891777/2104d35e-a4e1-11e4-9256-bfac04b76331.png)
